{% set name = "dingo-gw" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dingo-gw-{{ version }}.tar.gz
  sha256: da60632748a611ce564f364bcaee1dc36f8a8cfc802f1df3e5b9722a351acefa

build:
  entry_points:
    - dingo_generate_dataset = dingo.gw.dataset.generate_dataset:main
    - dingo_generate_dataset_dag = dingo.gw.dataset.generate_dataset_dag:main
    - dingo_merge_datasets = dingo.gw.dataset.utils:merge_datasets_cli
    - dingo_build_svd = dingo.gw.dataset.utils:build_svd_cli
    - dingo_generate_asd_dataset = dingo.gw.noise.generate_dataset:generate_dataset
    - dingo_estimate_psds = dingo.gw.noise.asd_estimation:download_and_estimate_cli
    - dingo_merge_asd_datasets = dingo.gw.noise.utils:merge_datasets_cli
    - dingo_train = dingo.gw.training:train_local
    - dingo_train_condor = dingo.gw.training.train_pipeline_condor:train_condor
    - dingo_append_training_stage = dingo.gw.training:append_stage
    - dingo_analyze_event = dingo.gw.inference:analyze_event
    - dingo_ls = dingo.gw.ls_cli:ls
    - dingo_pipe = dingo.gw.pipe.main:main
    - dingo_pipe_generation = dingo.gw.pipe.data_generation:main
    - dingo_pipe_sampling = dingo.gw.pipe.sampling:main
    - dingo_pipe_importance_sampling = dingo.gw.pipe.importance_sampling:main
    - dingo_result = dingo.gw.pipe.dingo_result:main
    - dingo_pipe_plot = dingo.gw.pipe.plot:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=62.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - numpy
    - pytorch
    - torchvision
    - glasflow
    - scipy
    - pyyaml
    - h5py
    - bilby
    - bilby_pipe
    - configargparse
    - corner
    - astropy
    - lalsuite >=7.11
    - pesummary
    - tensorboard
    - pyopenssl
    - cryptography
    - pycondor
    - gwpy
    - pycbc
    - pandas
    - threadpoolctl
    - scikit-learn

test:
  imports:
    - dingo
  commands:
    - pip check
    - dingo_generate_dataset --help
    - dingo_generate_dataset_dag --help
    - dingo_merge_datasets --help
    - dingo_build_svd --help
    - dingo_generate_asd_dataset --help
    - dingo_estimate_psds --help
    - dingo_merge_asd_datasets --help
    - dingo_train --help
    - dingo_train_condor --help
    - dingo_append_training_stage --help
    - dingo_analyze_event --help
    - dingo_ls --help
    - dingo_pipe --help
    - dingo_pipe_generation --help
    - dingo_pipe_sampling --help
    - dingo_pipe_importance_sampling --help
    - dingo_result --help
    - dingo_pipe_plot --help
  requires:
    - pip

about:
  home: https://github.com/dingo-gw/dingo
  summary: Deep inference for gravitational-wave observations
  description: |
    Dingo is a Python program for analyzing gravitational wave data using
    neural posterior estimation. It dramatically speeds up inference of
    astrophysical source parameters from data measured at gravitational-wave
    observatories. Dingo aims to enable the routine use of the most
    advanced theoretical models in analyzing data, to make rapid predictions
    for multi-messenger counterparts, and to do so in the context of
    sensitive detectors with high event rates.
  license: MIT
  license_file: LICENSE
  doc_url: https://dingo-gw.readthedocs.io/
  dev_url: https://github.com/dingo-gw/dingo

extra:
  recipe-maintainers:
    - stephengreen
    - max-dax
