{% set name = "msgpack-cxx" %}
{% set version = "6.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/msgpack/msgpack-c/archive/cpp-{{ version }}.tar.gz
    sha256: 797ad2285e8f7db3118563a879b9268567f0bd167b7b4a0c446e7f67a6a76451

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
  commands:
    - test -f $PREFIX/include/msgpack.hpp  # [unix]
    - test -f $PREFIX/lib/cmake/msgpack-cxx/msgpack-cxx-config.cmake  # [unix]
    - if not exist %LIBRARY_INC%\\msgpack.hpp exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\msgpack-cxx\\msgpack-cxx-config.cmake exit 1  # [win]

about:
  home: https://github.com/msgpack/msgpack-c
  license: BSL-1.0
  license_file: COPYING
  summary: MessagePack implementation for C++

extra:
  feedstock-name: msgpack-cxx
  recipe-maintainers:
    - traversaro
    - hmaarrfk
