{% set name = "sgw-sklearn-xarray" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mmann1123/sklearn-xarray/archive/refs/tags/v{{ version }}_gw.tar.gz  
  sha256: cad1c9e62e2700f0ae6299bafcae16aa3716063f784990118d10d97751ebb505

build:
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]

  host:

    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - xarray


test:
  imports:
    - sklearn_xarray

about:
  home: https://github.com/mmann1123/sklearn-xarray
  summary: 'a fork of sklearn-xarray for use in geowombat machine learning'
  description: |
    a fork of sklearn-xarray for use in geowombat machine learning
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/mmann1123/sklearn-xarray

extra:
  recipe-maintainers:
    - mmann1123
    - jgrss
