{% set name = "hole2" %}
{% set version = "2.3.2" %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://github.com/MDAnalysis/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: 67225d2134dc7a14a01c23b30022a0fc00d23f8adc1e5d617da330509ce64576

build:
  # only build for Linux and macOS
  skip: true # [win]
  number: {{ build_number }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - make
  host:
  run:

test:
  commands:
    # check for clean shutdown of hole and related programs
    - echo -en "\n" |  bln2gnu
    - echo -en "\n" |  capost2gnu
    - echo -en "\n" |  grd2gnu
    - echo -en "\n" |  hole
    - echo -en "exit\n" |  labqpt
    - echo -en "\n" |  make_post2gnu
    - echo -en "exit\n" |  make_post_map
    - echo -en "normal\nexit\n" |  qplot
    - echo -en "\n" |  qpt_conv
    - echo -en "\n" |  sos_triangle
    - echo -en "\n" |  vdwdot
    - echo -en "\n" |  vmd_triangles_to_lines
    # this one requires input and output args, empty files raise no errors
    - touch emptyfile && sph_process emptyfile emptyfile 

extra:
  recipe-maintainers:
    - ianmkenney
    - orbeckst
    - IAlibay
