{% set name = "hole2" %}
{% set version = "2.2.005" %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://github.com/MDAnalysis/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: 8fd0b49d7a5a976816a502c54287347d841addaf46a61ad93dd892e10fb4bf3e

build:
  # only build for Linux and macOS
  skip: true # [win]
  number: {{ build_number }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - make
  host:
  run:

test:
  commands:
    # check for clean shutdown of hole
    - echo "" | hole

extra:
  recipe-maintainers:
    - Ian Kenney <ikenney@asu.edu>
