{% set name = "hole2" %}
{% set version = "2.2.005" %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: "https://github.com/MDAnalysis/hole2.git"

build:
  # only build for Linux and macOS
  skip: true # [win]
  number: {{ build_number }}
  string: {{ [build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
  run:

test:
  commands:
    # check for clean shutdown of hole
    - echo "" | hole

extra:
  recipe-maintainers:
    - Ian Kenney <ikenney@asu.edu>
