{% set name = "hole2" %}
{% set version = "2.3.2" %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://github.com/MDAnalysis/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: 67225d2134dc7a14a01c23b30022a0fc00d23f8adc1e5d617da330509ce64576

build:
  # only build for Linux and macOS
  skip: true # [win]
  number: {{ build_number }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - make
  host:
  run:

test:
  commands:
    # check for clean shutdown of hole and related programs
    - bash -c 'bln2gnu <&-'
    - bash -c 'echo "" | capost2gnu'
    - bash -c 'echo "" | grd2gnu'
    - bash -c 'hole <&-'
    - bash -c 'labqpt <&-'
    - bash -c 'echo "" | make_post2gnu'
    - bash -c 'make_post_map <&-'
    - bash -c 'qplot <&-'
    - bash -c 'qpt_conv <&-'
    - bash -c 'sos_triangle <&-'
    - bash -c 'vdwdot <&-'
    - bash -c 'vmd_triangles_to_lines <&-'
    # this one requires input and output args, empty files raise no errors
    - touch emptyfile && sph_process emptyfile emptyfile 

extra:
  recipe-maintainers:
    - ianmkenney
    - orbeckst
    - IAlibay
