{% set name = "hole2" %}
{% set version = "2.3.0" %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://github.com/MDAnalysis/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: dd4dc83217639db8e2cde1dc65e235372870839999c0e9372ee609e183172dea

build:
  # only build for Linux and macOS
  skip: true # [win]
  number: {{ build_number }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - make
  host:
  run:

test:
  commands:
    # check for clean shutdown of hole
    - echo "" | hole

extra:
  recipe-maintainers:
    - Ian Kenney <ikenney@asu.edu>
