{% set name = "hole2" %}
{% set version = "2.3.2" %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://github.com/MDAnalysis/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: 67225d2134dc7a14a01c23b30022a0fc00d23f8adc1e5d617da330509ce64576

build:
  # only build for Linux and macOS
  skip: true  # [win]
  number: {{ build_number }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - make
  host:
  run:

test:
  commands:
    # check for clean shutdown of hole and related programs
    # check that the commands exist
    - command -v labqpt
    - command -v make_post2gnu
    - command -v make_post_map
    - qplot <&-
    - qpt_conv <&-
    - sos_triangle <&-
    - vdwdot <&-
    - vmd_triangles_to_lines <&-
    - bln2gnu <&-
    - hole <&-
    - echo "" | capost2gnu
    - echo "" | grd2gnu
    # this one requires input and output args, empty files raise no errors
    - touch emptyfile && sph_process emptyfile emptyfile
    - test -f ${CONDA_PREFIX}/share/hole2/rad/amberuni.rad
    - test -f ${CONDA_PREFIX}/share/hole2/rad/bondi.rad
    - test -f ${CONDA_PREFIX}/share/hole2/rad/hardcore.rad
    - test -f ${CONDA_PREFIX}/share/hole2/rad/simple.rad
    - test -f ${CONDA_PREFIX}/share/hole2/rad/xplor.rad

about:
  home: www.holeprogram.org
  license: Apache-2.0
  license_file: LICENSE
  summary: HOLE is a program that allows the analysis and visualisation of the pore dimensions of the holes through molecular structures of ion channels.

extra:
  recipe-maintainers:
    - ianmkenney
    - orbeckst
    - IAlibay
