{% set name = "jupyterlab-daw" %}
{% set version = "0.2.0" %}
{% set sha256 = "46f1bc24edf8e1b2c54157199658abbf0737494ddcf6f951edcf1a1c97af031c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab_daw/jupyterlab_daw-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.4.0
    - jupyterlab >=3.4.7,<4
    - pip
    - python >=3.7,<4.0
  run:
    - python >=3.7,<4.0

test:
  requires:
    - jupyterlab =3
    - pip
    - m2-grep  # [win]
  imports:
    - jupyterlab_daw
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "jupyterlab-daw.*v{{ version.replace(".", "\\.") }}.*enabled.*OK.*jupyterlab_daw" labextensions

about:
  home: https://github.com/benbovy/jupyterlab-daw
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Audio and music in JupyterLab
  description: A JupyterLab extension providing Digital Audio Workstation (DAW) features
  dev_url: https://github.com/benbovy/jupyterlab-daw

extra:
  recipe-maintainers:
    - benbovy
