{% set version = "0.0.11" %}

package:
  name: auditwheel-emscripten
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/a/auditwheel-emscripten/auditwheel_emscripten-{{ version }}.tar.gz
    sha256: 0bacaf0e800e18b04ce19d89c91a82243d86445d1758421ff02d715736455c1b
  # TODO: remove after https://github.com/ryanking13/auditwheel-emscripten/pull/10
  - fn: LICENSE-auditwheel-emscripten-{{ version }}
    url: https://raw.githubusercontent.com/ryanking13/auditwheel-emscripten/{{ version }}/LICENSE
    sha256: 1f256ecad192880510e84ad60474eab7589218784b9a50bc7ceee34c2b91f1d5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.8
  run:
    - leb128
    - packaging
    - pyodide-cli
    - python >=3.8
    - typer
    - wheel

test:
  imports:
    - auditwheel_emscripten
  commands:
    - pip check
    - pyodide auditwheel --help
  requires:
    - pip

about:
  home: https://pypi.org/project/auditwheel-emscripten
  summary: auditwheel-like tool for Pyodide
  license: MPL-2.0
  license_file: LICENSE-auditwheel-emscripten-{{ version }}
  dev_url: https://github.com/ryanking13/auditwheel-emscripten

extra:
  recipe-maintainers:
    - bollwyvl
