{% set name = "BitMagic" %}
{% set version = "7.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tlk00/{{name}}/archive/refs/tags/v{{version}}.tar.gz
  sha256: 5e59507a01a8295bb57aebcf557a4a25b992244736f7924300cdb9635f1b2780

build:
  number: 0

# does not need *anything*
requirements:
  build:
  host:
  run:

test:
  # check that files exist
  commands:
    - test -e ${PREFIX}/inlclude/bitmagic/bm.h  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\bm\bm.h (exit 1) # [win]

about:
  home: https://github.com/tlk00/BitMagic
  summary: 'BitMagic is a general data science components library'
  description: |
BitMagic was created as a Algebra of Sets toolkit for Information Retrieval 
but currently evolved into a more general Data Science components library 
for memory compact structures and algorithms on succinct data vectors. 
BitMagic implements compressed bit-vectors and containers (vectors) 
based on ideas of bit-slicing transform, Rank-Select compression and 
logical computing on memory compressed models.

  license: Apache-2.0	
  license_family: Apache
  license_file: LICENSE


extra:
  recipe-maintainers:
    - DerThorsten
