{% set name = "caped-ai-augmentations" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/caped-ai-augmentations-{{ version }}.tar.gz
  sha256: c9e4d218830d878970b8c12da07b5d9956a06d8be826bb83f3486d5a788fd31b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - albumentations
    - dask-core
    - natsort
    - opencv
    - photutils
    - python >=3.9
    - scikit-learn
    - scipy

test:
  imports:
    - caped_ai_augmentations
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kapoorlabs-CAPED/caped-ai-augmentations/
  summary: |
    Augmentations for volume, planar segmentation, classification image
    segmentation and associated csv file of oneat clicks.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
