{% set name = "suxarray" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d48ae7587db88d14b7c8eaca4152b5474f33d3fe9f43f613be0ee61f6ce988a 

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - suxarray
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/cadwrdeltamodeling/suxarray
  summary: 'SCHISM grid extension of uxarray'
  description: |
    suxarray is an extension of uxarray for SCHISM grids and data.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://cadwrdeltamodeling.github.io/suxarray/
  dev_url: https://github.com/cadwrdeltamodeling/suxarray

extra:
  recipe-maintainers:
    - kjnam
