{% set name = "PCMSolver" %}
{% set version = "1.2.3" %}
{% set sha256 = "4e905e7b6a229142179e185b67248eadac936c45d5ccb69ef6d18545cd3c6628" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/{{ name }}/{{ name|lower }}/archive/v{{ version }}.tar.gz
  url: https://github.com/loriab/pcmsolver/archive/v123_plus.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  #binary_relocation: true
  skip: true  # [py!=39]
  run_exports:
    - {{ pin_subpackage('pcmsolver', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - ninja
  host:
    # below two are header-only deps that pcmsolver supplies when missing
    # - boost-cpp
    # - eigen
    - python
    - zlib
  run:
    - python

test:
  imports:
    - pcmsolver
  files:
    - molecule.inp
  commands:
    - ls -l $PREFIX/lib                                      # [unix]
    - ls -l $PREFIX/share/cmake/PCMSolver                    # [unix]
    - ls -l $SP_DIR/pcmsolver                                # [unix]
    - dir "%PREFIX%\Library"                                 # [win]
    - dir "%PREFIX%"\Library\include                         # [win]
    - dir %SP_DIR%\pcmsolver                                 # [win]
    # Verify library
    - test -L $PREFIX/lib/libpcm$SHLIB_EXT                   # [unix]
    - test ! -f $PREFIX/lib/libpcm.a                         # [unix]
    - test -f $PREFIX/bin/go_pcm.py                          # [unix]
    - test -f $PREFIX/bin/run_pcm                            # [unix]
    - test -f $SP_DIR/pcmsolver/pcmparser.py                 # [unix]
    - if not exist %PREFIX%\\Library\\lib\\pcm.lib exit 1    # [win]
    - if not exist %PREFIX%\\Library\\bin\\pcm.dll exit 1    # [win]
    - if not exist %PREFIX%\\Library\\bin\\go_pcm.py exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\run_pcm.exe exit 1  # [win]
    - if not exist %SP_DIR%\\pcmsolver\\pcmparser.py exit 1  # [win]
    # Verify accessories
    - test -e $PREFIX/include/PCMSolver/pcmsolver.h          # [unix]
    - if not exist %PREFIX%\\Library\\include\\PCMSolver\\pcmsolver.h exit 1  # [win]
    - test -e $PREFIX/share/cmake/PCMSolver/PCMSolverConfig.cmake  # [unix]
    - if not exist %PREFIX%\\Library\\share\\cmake\\PCMSolver\\PCMSolverConfig.cmake exit 1  # [win]
    # Inspect linkage
    - ldd -v $PREFIX/lib/libpcm$SHLIB_EXT                    # [linux and build_platform == target_platform]
    - otool -L $PREFIX/lib/libpcm$SHLIB_EXT                  # [osx]
    # Actually test
    - python $PREFIX/bin/go_pcm.py --inp molecule.inp --exe $PREFIX/bin  # [unix]
    - cat molecule.out                                       # [unix]

about:
  home: https://github.com/PCMSolver/pcmsolver
  dev_url: https://github.com/PCMSolver/pcmsolver
  doc_url: https://pcmsolver.readthedocs.io/en/stable/
  doc_source_url: https://github.com/PCMSolver/pcmsolver/tree/master/doc
  license: LGPL-3.0-only
  license_url: https://opensource.org/license/lgpl-3-0/
  license_file: LICENSE
  license_family: LGPL
  summary: "R. Di Remigio & L. Frediani's Polarizable Continuum Model (PCM) API"

extra:
  recipe-maintainers:
    - loriab
    - robertodr
