{% set name = "nlpannotator" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nlpannotator-{{ version }}.tar.gz
  sha256: 16406d8cfb63e0dd86de5dd17ee59074d797c2cf52825edc1853d56ab1c4f0ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
  run:
    - python >=3.7,<4.0
    - spacy <3.5.0,>=3.4.0
    - stanza
    - python-flair
    - somajo >=2.0
    - treetaggerwrapper
    - jsonschema
    - importlib-resources >=5.8

test:
  imports:
    - nlpannotator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ssciwr.github.io/argumentation-management/
  summary: Annotator combining different NLP pipelines
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - iulusoy
