{% set name = "nlpannotator" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nlpannotator-{{ version }}.tar.gz
  sha256: 110b10e0d25616fede0c7bf3f927d38035fd0af0b5df3c00ffdda366697aea56

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
  run:
    - python >=3.7,<4.0
    - spacy <3.5.0,>=3.4.0
    - stanza
    - python-flair
    - SoMaJo
    - treetaggerwrapper
    - jsonschema
    - importlib-resources >=5.8

test:
  imports:
    - nlpannotator
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  home: https://ssciwr.github.io/argumentation-management/
  summary: Annotator combining different NLP pipelines
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - iulusoy
