{% set version = "1.51.7" %}

package:
  name: statlite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/starlite/starlite-{{ version }}.tar.gz
  sha256: 7e4b25f002d8edbf928f1588d1e7eb85375c6ed0834c190072af662403110af6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8
  run:
    - anyio >=3
    - fast-query-parsers
    - httpx >=0.22
    - importlib-metadata
    - msgspec
    - multidict >=6.0.2
    - pydantic
    - pydantic-factories
    - python >=3.8
    - pyyaml
    - typing-extensions

test:
  imports:
    - starlite
  commands:
    - pip check
    - mypy -p --ignore-missing-imports
  requires:
    - pip
    - mypy

about:
  home: https://github.com/starlite-api/starlite
  summary: Performant, light and flexible ASGI API Framework
  license: MIT
  license_file: LICENSE
  doc_url: https://docs.starliteproject.dev

extra:
  recipe-maintainers:
    - bollwyvl
