{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}
# name for conda package (i.e. `conda install -c conda-forge <project_name>`)
{% set project_name = "r-evalhyd" %}
# name of repository
{% set repository_name = "evalhyd-r" %}
# name for python package (i.e. `python -c "import <package_name>"`)
{% set package_name = "evalhyd" %}
{% set version = "0.1.0.0" %}
{% set sha256 = "eea910af43fcd6ebed2e519d843aa3e66557fb6fb947733aaf6b5e33cda56f6c" %}

package:
  name: {{ project_name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/{{ repository_name }}/-/archive/v0.1.0.0-rc.4/{{ repository_name }}-v0.1.0.0-rc.4.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  merge_build_host: True                              # [win]
  script_env:
    - TMPDIR=${PREFIX}/tmp
    - EVALHYD_R_VENDOR_XTL=FALSE
    - EVALHYD_R_VENDOR_XTENSOR=FALSE
    - EVALHYD_R_VENDOR_XTENSOR_R=FALSE
    - EVALHYD_R_VENDOR_EVALHYD_CPP=FALSE
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}                       # [build_platform != target_platform]
    - {{ compiler('cxx') }}                           # [unix]
    - {{ compiler('m2w64_cxx') }}                     # [win]
    - {{ posix }}filesystem                           # [win]
    - {{ posix }}make
    - {{ posix }}sed                                  # [win]
    - {{ posix }}coreutils                            # [win]
    - {{ posix }}zip                                  # [win]
  host:
    - r-base
    - r-matrix >=1.1_0
    - r-rcpp >=0.11.0
    - xtl >=0.7.5
    - xtensor >=0.24.6
    - xtensor-r >=0.14.2
    - r-xtensor >=0.14.1
    - evalhyd-cpp ==0.1.0
  run:
    - r-base
    - {{ native }}gcc-libs                            # [win]
    - {{ pin_compatible('xtensor-r', max_pin='x.x') }}
    - r-rcpp >=0.11.0

test:
  commands:
    - $R -e "library('{{ package_name }}')"           # [unix]
    - "\"%R%\" -e \"library('{{ package_name }}')\""  # [win]

about:
  home: https://hydrogr.github.io/evalhyd
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENCE.rst
  summary: R bindings for evalhyd, a C++ library to evaluate streamflow predictions
  description: |
    An R package to evaluate deterministic and probabilistic 
    streamflow predictions
  doc_url: https://hydrogr.github.io/evalhyd/r
  dev_url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/{{ repository_name }}

extra:
  recipe-maintainers:
    - ThibHlln
