{% set name = "libde265" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/strukturag/libde265/releases/download/v{{ version }}/libde265-{{ version }}.tar.gz
  sha256: 29bc6b64bf658d81a4446a3f98e0e4636fd4fd3d971b072d440cef987d5439de

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
    requires:
        - git

about:
  home: http://www.libde265.org/
  summary: 'Open h.265 video codec implementation'
  description: |
    libde265 is an open source implementation of the h.265 video codec.
    It is written from scratch and has a plain C API to enable a simple
    integration into other software. libde265 supports WPP and tile-based
    multithreading and includes SSE optimizations. The decoder includes all
    features of the Main profile and correctly decodes almost all conformance
    streams.
  license:  LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING
  dev_url: https://github.com/strukturag/libde265

extra:
  recipe-maintainers:
    - frmdstryr
