package:
    name: metis-aster
    version: 5.1.0
source:
    sha256: 1b295f9ce260c19d2d93fb2430be4139496c56f58f74ef7956ccd26c854fcc2e
    #url: http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz
    url: https://netix.dl.sourceforge.net/project/prereq/metis-5.1.0_aster4.tar.gz
build:
    binary_relocation: true
    ignore_run_exports:
        - libstdcxx-ng
    number: 0
    run_exports:
        - metis-aster >=5.1.0,<5.2.0a0
requirements:
    build:
        - gcc 8  # [linux]
        - gxx 8  # [linux]
        - gfortran 8  # [linux]
        - sysroot_linux-64 =2.17
    host:
        - make
    run:
        - libgcc-ng >=7.5.0
test:
    commands:
        - test -f $PREFIX/metis-aster/bin/graphchk
        - test -f $PREFIX/metis-aster/bin/cmpfillin
        - test -f $PREFIX/metis-aster/bin/mpmetis
        - test -f $PREFIX/metis-aster/bin/gpmetis
        - test -f $PREFIX/metis-aster/bin/ndmetis
        - test -f $PREFIX/metis-aster/bin/gpmetis
        - test -f $PREFIX/metis-aster/bin/m2gmetis
        - test -f $PREFIX/metis-aster/include/metis.h
        - test -f $PREFIX/metis-aster/lib/libmetis.a
    source_files:
        - graphs
about:
    description: 'METIS is a set of serial programs for partitioning graphs, partitioning
        finite element meshes, and producing fill reducing orderings for sparse
        matrices. The algorithms implemented in METIS are based on the multilevel
        recursive-bisection, multilevel k-way, and multi-constraint partitioning
        schemes developed in our lab. Modified to add long integer support for Code-Aster
        '
    doc_url: http://glaros.dtc.umn.edu/gkhome/metis/metis/faq
    src_url: https://sourceforge.net/p/prereq/metis
    home: http://glaros.dtc.umn.edu/gkhome/metis/metis/overview
    license: Apache-2.0
    license_file: LICENSE.txt
    summary: METIS - Serial Graph Partitioning and Fill-reducing Matrix Ordering with Code_Aster modification (LONGINT support)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ldallolio
