{% set version = "1.7.1" %}

package:
  name: chemps2
  version: {{ version }}

source:
  fn: CheMPS2-v{{ version }}.tar.gz
  url: https://github.com/SebWouters/CheMPS2/archive/v{{ version }}.tar.gz
  sha256: 16894a0ade6b5f1d3cf06b95723567558bdddf43ad25eca067bced5ab35b3a5e

build:
  number: 5
  binary_relocation: true
  skip: true  # [win and linux]

requirements:
  build:
    - cmake >=2.8.11
    - gcc  # [osx]
    - hdf5 1.8.17|1.8.17.*
    - zlib 1.2.*
  run:
    - hdf5 1.8.17|1.8.17.*
    - libgcc  # [osx]
    - zlib 1.2.*

test:
  commands:
    # Verify libraries and executable.
    - test -f $PREFIX/lib/libchemps2.so  # [linux]
    - test -f $PREFIX/lib/libchemps2.dylib  # [osx]
    - test -f $PREFIX/bin/chemps2

about:
  home: http://sebwouters.github.io/CheMPS2
  license: GNU General Public License v2 or later (GPLv2+)
  license_family: GPL2
  license_file: LICENSE
  summary: "S. Wouters' spin-adapted implementation of DMRG for ab initio quantum chemistry"

extra:
  recipe-maintainers:
    - loriab

