{% set name = "levenshtein" %}
{% set version = "0.20.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Levenshtein-{{ version }}.tar.gz
  sha256: 70a8ad5e28bb76d87da1eb3f31de940836596547d6d01317c2289f5b7cd0b0ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - scikit-build >=0.13.0
    - pip
  run:
    - python >=3.6
    - rapidfuzz <3.0.0,>=2.3.0

test:
  imports:
    - levenshtein
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxbachmann/Levenshtein
  summary: Python extension for computing string edit distances and similarities.
  license: GPL-2.0 AND MIT
  license_file:
    - COPYING
    - extern/rapidfuzz-cpp/LICENSE

extra:
  recipe-maintainers:
    - julian-belina
