{% set name = "cross_cal_resourcesat" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cross_cal_resourcesat-{{ version }}.tar.gz
  sha256: 9f35a22f20443108713e954ad3b80a362f885e5b18329a7b11cedfa4eba47d90

build:
  # noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - gdal  3.5.0 py310h2e4f8af_4  # [osx and py==39]
    - gdal  3.5.0 py310h45d78e8_4  # [linux and py==39]
    - gdal  3.5.0 py310h2a306c7_4  # [win and py==39]
    - gdal  2.4.4 py37h622575a_1  # [osx and py==37]
    - gdal  2.4.4 py38h57202bd_1  # [osx and py==38]
    - gdal  2.4.4 py37hf8c3989_1  # [linux and py==37]
    - gdal  2.4.4 py38hfe926b7_1  # [linux and py==38]

  run:
    - python >=3.7
    - numpy
    - rasterio
    - glob2
    - regex
    - gdal  3.5.0 py310h2e4f8af_4  # [osx and py==39]
    - gdal  3.5.0 py310h45d78e8_4  # [linux and py==39]
    - gdal  3.5.0 py310h2a306c7_4  # [win and py==39]
    - gdal  2.4.4 py37h622575a_1  # [osx and py==37]
    - gdal  2.4.4 py38h57202bd_1  # [osx and py==38]
    - gdal  2.4.4 py37hf8c3989_1  # [linux and py==37]
    - gdal  2.4.4 py38hfe926b7_1  # [linux and py==38]
test:
  imports:
    - cross_cal_resourcesat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/akhi9661/cross_cal_resourcesat
  summary: A python package to cross calibrate ResourceSat 2 sensors like LISS III, AWiFS or LISS IV.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akhi9661
