channel_sources:
  - conda-forge/label/libint_dev,conda-forge
# note for review: I'd engage the following since the src isn't a proper upstream release,
#   but I don't think it's enough to get this recipe into branch `dev` upon feedstock creation
#channel_targets:
#  - conda-forge psi4_dev
mkl:
  - 2022.1.0  # [win]
dftd4:
  # provides b97-3c parameters
  - 3.5.0
libint:
  # provides rt-switchable ordering (src) and derivative integrals (build)
  - 2.7.3dev1
pylibefp:
  # 0.6.3 can detect py311
  - 0.6.2
geometric:
  # new API
  - "1.0"
pymdi:
  # breaking API change
  - "1.2"
