c_compiler_version:
  - 10                         # [linux]
cxx_compiler_version:
  - 10                         # [linux]
fortran_compiler_version:
  - 10                         # [linux]
libint:
  - 2.7.3dev1
channel_sources:
  - conda-forge/label/libint_dev,conda-forge
