channel_sources:
  - conda-forge/label/libint_dev,conda-forge
mkl:
  - 2022.1.0  # [win]
dftd4:
  # provides b97-3c parameters
  - 3.5.0
libint:
  # provides rt-switchable ordering (src) and derivative integrals (build)
  - 2.7.3dev1
pylibefp:
  # 0.6.3 can detect py311
  - 0.6.2
geometric:
  # new API
  - "1.0"
pymdi:
  # breaking API change
  - "1.2"
