{% set name = "psi4" %}
{% set version = "1.8a1.dev30" %}
{% set sha256 = "a4d9e34c93eb427c3b6ba45221f71bd3f1d6d3c227188df37ade408800dd46ce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/loriab/psi4/archive/cf_iterations.tar.gz
    # url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
  - url: https://github.com/psi4/iomp5md/archive/31b4ccb.tar.gz               # [win]
    sha256: d9c6ad3976183f54b676335885d8557d67ca7b25ac4115b91b4cc42281d95f7c  # [win]
    folder: external_src                                                      # [win]

build:
  number: 0
  binary_relocation: true
  ignore_run_exports:
    - libint

# bkgd for review: the libint story
# * this recipe is using a libint dev package for reasons at https://github.com/conda-forge/libint-feedstock/issues/15
# * libint_dev pkg has a run_exports `x`, which is true for the package in general
# * but for the time being in case of unfinalized API, it's prudent to pin req/run to exact, hence the ignore_run_exports above

# bkgd for review: the fortran story
# * psi4 has no fortran code and no fortran required dependencies (besides blas/lapack)
# * it does have optional functionality-expanding fortran dependencies like dkh (recipe alongside) that are packaged separately
# * this recipe omits the fortran compiler since C++ compiler can do the linking and because on windows,
#   the msvc+gfortran combination hits https://gitlab.kitware.com/cmake/cmake/-/issues/17810

# bkgd for review: the general blas story
# * psi4 is heavily performance-dependent on the blas/lapack implementation
# * we've been packaging on conda with mkl for the past 7y
# * while the build system allows any blas impl, we emit "untested" warnings for non-MKL, and last openblas test 5y ago had threading oversubscriptions
# * so while we're open to multiple impl in future and have been specifying generic "libblas" in deps like dkh, we'd like to support only mkl in psi4 for now

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make                                   # [not win]
    - ninja                                  # [win]
    - llvm-openmp                            # [not win]
  host:
    - eigen
    - boost-cpp
    - mkl-devel                              # [not win]
    - mkl-devel {{ mkl }}                    # [win]
    - mkl                                    # [not win]
    - mkl {{ mkl }}                          # [win]
    - pybind11
    - pybind11-abi
    - python
    # qc req'd
    - gau2grid
    - libint {{ libint }}
    - libxc-c
    - optking
    - qcelemental
    - qcengine
    # qc opt'l, build-time
    - dkh
  run:
    - llvm-openmp                            # [not win]
    - intel-openmp                           # [win]
    - libblas * *mkl
    - mkl                                    # [not win]
    - mkl {{ mkl }}                          # [win]
    - msgpack-python
    - networkx
    - numpy
    - python
    - scipy
    # qc
    - libint {{ libint }}
    - {{ pin_compatible('optking', upper_bound='0.5') }}
    - {{ pin_compatible('qcelemental', upper_bound='0.5') }}
    - {{ pin_compatible('qcengine', upper_bound='0.5') }}
  run_constrained:
    - pytest >=7.0.1
    # qc opt'l, run-time
    - pylibefp =={{ pylibefp }}
    - dftd4-python >={{ dftd4 }}
    - geometric >={{ geometric }}
    - pymdi >={{ pymdi }}

test:
  imports:
    - psi4
  requires:
    - pytest
    - pytest-xdist
    - m2w64-binutils                                                     # [win]   # provides objdump.exe
    # qc runtime opt'l
    - pyddx                                                              # [unix]
    - dftd3-python                                                       # [unix]
    - dftd4-python                                                       # [unix]
    - toml                                                                         # needed for qcengine/dftd4-python interface
    - pylibefp
    - gcp-correction                                                     # [unix]
    - geometric
    - pymdi
  commands:
    - ls -l $PREFIX/lib                                                  # [unix]
    - ls -l $PREFIX/share/cmake/psi4                                     # [unix]
    - ls -l $SP_DIR/psi4                                                 # [unix]
    - dir %PREFIX%\\Library\\lib                                         # [win]
    - dir %PREFIX%\\Library\\share\\cmake\\psi4                          # [win]
    - dir %SP_DIR%\\psi4                                                 # [win]
    # Verify module
    - test -f $SP_DIR/psi4/core*.so                                      # [unix]
    - test -f $SP_DIR/psi4/driver/driver.py                              # [unix]
    - if not exist %SP_DIR%\\psi4\\core*.pyd exit 1                      # [win]
    - if not exist %SP_DIR%\\psi4\\driver\\driver.py exit 1              # [win]
    # Verify executable
    - test -f $PREFIX/bin/psi4                                           # [unix]
    - $PREFIX/bin/psi4 --version                                         # [unix]
    - $PREFIX/bin/psi4 --module                                          # [unix]
    - if exist %PREFIX%\\Scripts\\psi4 exit 1                            # [win]
    - if not exist %PREFIX%\\Scripts\\psi4-script.py exit 1              # [win]   # aka bin/psi4
    - if not exist %PREFIX%\\Scripts\\psi4.exe exit 1                    # [win]
    - "%PREFIX%\\Scripts\\psi4.exe --version"                            # [win]
    - "%PREFIX%\\Scripts\\psi4.exe --module"                             # [win]
    - python -c "import psi4;print(psi4.executable)"
    # Verify accessories
    - test -f $PREFIX/include/psi4/psi4-dec.h                            # [unix]
    - test -f $PREFIX/share/cmake/psi4/psi4Config.cmake                  # [unix]
    - test -f $PREFIX/share/cmake/TargetLAPACK/TargetLAPACKConfig.cmake  # [unix]
    - test -f $PREFIX/share/psi4/basis/cc-pvdz.gbs                       # [unix]
    - if not exist %PREFIX%\\Library\\include\\psi4\\psi4-dec.h exit 1   # [win]
    - if not exist %PREFIX%\\Library\\share\\cmake\\psi4\\psi4Config.cmake exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\cmake\\TargetLAPACK\\TargetLAPACKConfig.cmake exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\psi4\\basis\\cc-pvdz.gbs exit 1  # [win]
    # Inspect linkage
    - ldd -v $SP_DIR/psi4/core*.so                                       # [linux]
    - otool -L $SP_DIR/psi4/core*.so                                     # [osx]
    - objdump.exe -p %SP_DIR%\\psi4\\core.*.pyd | findstr /i "dll"       # [win]
    # Actually test
    - python -c "from psi4 import core; core.set_num_threads(42); assert core.get_num_threads() == 42"
    - MKL_CBWR=AVX pytest -rws -v --durations=20 --color yes -n auto $SP_DIR/psi4 -m "smoke"  # [unix]
    - pytest -rws -v --durations=20 --color yes -n auto %SP_DIR%\\psi4 -m "smoke and not d2ints"  # [win]

about:
  home: http://psicode.org
  dev_url: https://github.com/psi4/psi4
  doc_url: http://psicode.org/psi4manual/master/index.html
  doc_source_url: https://github.com/psi4/psi4/tree/master/doc/sphinxman/source
  license: LGPL-3.0-only
  license_url: https://opensource.org/license/lgpl-3-0/
  license_file:
    - COPYING
    - COPYING.LESSER
  license_family: LGPL
  summary: "Open-Source Quantum Chemistry - an electronic structure package in C++ driven by Python"
  description: |
    Psi4 is an open-source suite of ab initio quantum chemistry programs designed for efficient,
    high-accuracy simulations of a variety of molecular properties. We can routinely perform computations
    with more than 2500 basis functions running serially or on multi-core machines. With computationally
    demanding portions written in C++, Pybind11 exports many of the C++ classes into Python, and a
    flexible Python driver, Psi4 strives to be friendly to both users and developers.

extra:
  recipe-maintainers:
    - loriab

#######

#          commands:
#              # Actually test
#              - PASSFAIL="--passfail"           # [linux]
#              - PASSFAIL=""                     # [osx]  # Mac threading occasionally bizarre
#              - python $PREFIX/share/psi4/scripts/test_threading.py --passfail --ldd  # [py3k]
#              - python $PREFIX/share/psi4/scripts/test_threading.py ${PASSFAIL} --psiapi -n6  # [py3k]
#              - python $PREFIX/share/psi4/scripts/test_threading.py ${PASSFAIL} --psithon -n6  # [py3k and not osx]

# Notes
# -----

# * The following optional runtime deps were included in req/run of the psi4::psi4 package but are omitted in conda-forge::psi4
#   * pytest
#   * dftd3
#   * gcp
#   * dftd4 (installer only)
