channel_priority: strict
provider:
  linux: azure
  osx: azure
  win: azure
  linux_ppc64le: None
  linux_aarch64: None
  all: None
build_platform:
  osx_64: linux_64
  win_64: linux_64
  linux_64: linux_64
test_on_native_only: True
#azure:
#  settings_win:
#    pool:
#      vmImage: windows-2019