channel_priority: strict
provider:
  linux_64: azure
  osx_64: azure
  win_64: azure
  linux_ppc64le: None
  linux_aarch64: None
  linux_64_cuda_102: None
  linux_64_centos7: None
  all: None
azure:
  settings_win:
    pool:
      vmImage: windows-2019