conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
channels:
  # sources selects the channels to pull packages from, in order.
  sources:
    - pytorch
    - conda-forge
    - defaults
