channel_priority: strict
azure:
  settings_win:
    pool:
      vmImage: windows-2019
channels:
  # sources selects the channels to pull packages from, in order.
  sources:
    - conda-forge
    - defaults
    - pytorch