{% set name = "Remotery" %}
{% set organization = "Celtoys" %}
{% set version = "1.2.1" %}
{% set sha256 = "5740532229fe4da8d8ab8e310cc6a38d3f198f59314f5ecf1a072aca25f91709" %}

package:
   name: {{ name|lower }}-split

source:
  url: https://github.com/{{ organization }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-build-Add-a-CMake-setup.patch
build:
  number: 0

outputs:
  - name: {{ name|lower }}
    version: {{ version }}
    script: build_remotery.sh   # [unix]
    script: build_remotery.bat  # [win]

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]

    test:
      commands:
        - echo "TODO"

outputs:
  - name: {{ name|lower }}-static
    version: {{ version }}
    script: build_remotery.sh   # [unix]
    script: build_remotery.bat  # [win]

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]

    test:
      commands:
        - echo "TODO"

about:
  home: https://github.com/{{ organization }}/{{ name }}/
  summary: 'Single C file, Realtime CPU/GPU Profiler with Remote Web Viewer'
  description: |
    A realtime CPU/GPU profiler hosted in a single C file with a viewer that runs in a web browser.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/{{ organization }}/{{ name }}/

extra:
  recipe-maintainers:
    - jjerphan
    - DerThorsten
    - JohanMabille
