{% set name = "bluesky-adaptive" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bluesky-adaptive-{{ version }}.tar.gz
  sha256: b12e7cae7120b14cf93cc21260af4313cc8d891c04e9468c6fa98a92d906248f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - bluesky
    - bluesky-live
    - bluesky-widgets
    - bluesky-kafka
    - bluesky-queueserver-api
    - xkcdpass
    - tiled
    - numpy
    - pydantic

test:
  imports:
    - bluesky_adaptive
    - bluesky_adaptive.agents.base
    - bluesky_adaptive.adjudicators.base
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bluesky/bluesky-adaptive
  summary: Tools for writing adaptive plans
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maffettone
    - mrakitin
