{% set name = "napatrackmater" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napatrackmater-{{ version }}.tar.gz
  sha256: 1255d6da38980dec3dede71173fcf93d5a5566af241f6dffc325106e2da8cc4e

build:
  entry_points:
    - track = napatrackmater.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas
    - napari
    - pyqt
    - natsort
    - scikit-image
    - scipy
    - tifffile
    - matplotlib-base
    - ffmpeg-python
    - imageio-ffmpeg
    - dask-core
    - lmfit
    - seaborn
    - perfmetrics

test:
  imports:
    - napatrackmater
  commands:
    - pip list
    - pip check
    - track --help
  requires:
    - pip

about:
  home: https://github.com/kapoorlab/NapaTrackMater/
  summary: Import Trackmate XML files for Track Visualization and analysis in Napari.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
