{% set name = "csvlint" %}
{% set version = "1.2.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 886c87441af105065e620386434ae2cd9d9c69cfcd532335ae52f1cd15f419c8

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies -n $PREFIX/bin {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby >=2.5, <3.3
  run:
    - ruby >=2.5, <3.3
    - rb-rainbow

test:
  commands:
    - csvlint help

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.md
  summary: A ruby gem to support validating CSV files to check their syntax and contents.
  doc_url: https://www.rubydoc.info/gems/csvlint
  dev_url: https://github.com/Data-Liberation-Front/csvlint.rb

extra:
  recipe-maintainers:
    - svengiegerich
