{% set name = "mapwidget" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mapwidget-{{ version }}.tar.gz
  sha256: b4c8d33c376110be907283290a3791bb7a71247ea7712877a8039b9f8e5fcab6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - anywidget

test:
  imports:
    - mapwidget
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/giswqs/mapwidget
  summary: Custom Jupyter widgets for creating interactive maps
  license: MIT
  license_file: LICENSE
  description: Custom Jupyter widgets for creating interactive maps with popular JavaScript mapping libraries, such as leaflet, mapbox, maplibre, cesium, and openlayers.
  doc_url: https://mapwidget.gishub.org
  dev_url: https://github.com/giswqs/mapwidget

extra:
  recipe-maintainers:
    - giswqs
