{% set name = "power-grid-model" %}
{% set version = "1.4.69" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/power-grid-model-{{ version }}.tar.gz
  sha256: 40ba3f8e98b2e883f8f8015064c13fa2f148141c778df2511c4a952ecede07de

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python >=3.7
    - setuptools
    - wheel
    - pip
    - eigen
    - boost-cpp
  run:
    - python >=3.7
    - numpy >=1.21.0

test:
  imports:
    - power_grid_model
  commands:
    - pip check
    - pytest
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pip
    - pytest
    - pytest-cov

about:
  summary: Python/C++ library for distribution power system analysis
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TonyXiang8787
