{% set name = "power-grid-model" %}
{% set version = "1.4.69" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/power-grid-model-{{ version }}.tar.gz
  sha256: 40ba3f8e98b2e883f8f8015064c13fa2f148141c778df2511c4a952ecede07de

build:
  skip: true  # [py<37 or win32 or ppc64le]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - eigen                                  # [build_platform != target_platform]
    - boost-cpp                              # [build_platform != target_platform]

  host:
    - python
    - setuptools
    - wheel
    - pip
    - eigen
    - boost-cpp
  run:
    - python
    - numpy >=1.21.0

test:
  imports:
    - power_grid_model
  commands:
    - pip check
    - pytest
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pip
    - pytest
    - pytest-cov

about:
  home: https://lfenergy.org/projects/power-grid-model/
  summary: Python/C++ library for distribution power system analysis
  license: MPL-2.0
  license_file: LICENSE
  doc_url: https://power-grid-model.readthedocs.io/
  dev_url: https://github.com/PowerGridModel/power-grid-model

extra:
  recipe-maintainers:
    - TonyXiang8787
    - mgovers
    - nitbharambe
    - petersalemink95
