{% set name = "pygoss" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/p/pygoss/pygoss-{{ version }}.tar.gz"
  sha256: bb63b5f135b11f3366b92c3bc24c735f57c503ff6d04bb7de25ebdf053bd5d55

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"
  skip: true  # [win]
  skip:  # [py<37]
requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - pybind11
    - ninja
    - scikit-build
    - cmake
    - libgomp    # [linux]
    - llvm-openmp     # [osx]
  run:
    - python
    - numpy
    - modelparameters
    - gotran
    - rich-click
    - pydantic
    - cppyy


test:
  imports:
    - goss

  requires:
    - pip

  commands:
    - pip check

about:
  home: https://github.com/ComputationalPhysiology/goss
  summary: goss is python wrapper around a C++ library for solving ordinary differential equations with a variety of different schemes
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  doc_url: https://computationalphysiology.github.io/goss
  dev_url: https://github.com/ComputationalPhysiology/goss

extra:
  recipe-maintainers:
    - finsberg
