{% set name = "gotran" %}
{% set version = "2023.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: df1d843fd43b6037f99b1b3564d553e7ee019b918d6a24e128515490f89dc345

build:
  number: 0
  noarch: python
  script: python -m pip install -v --no-deps .

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - modelparameters
    - numpy
    - scipy
    - packaging

test:
  imports:
    - gotran

  requires:
    - pip

  commands:
    - pip check

about:
  home: https://github.com/ComputationalPhysiology/gotran
  summary: Library for declaring and translating ODEs
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  doc_url: https://computationalphysiology.github.io/gotran/
  dev_url: https://github.com/ComputationalPhysiology/gotran

extra:
  recipe-maintainers:
    - finsberg
