{% set name = "dkh" %}
{% set version = "1.2" %}
{% set sha256 = "275d575a2cd52f75a1696554a2f638d91b4c60ed1744a46e6956f09ad0458369" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/{{ name }}/{{ name|lower }}/archive/v{{ version }}.tar.gz
  url: https://github.com/psi4/dkh/archive/6f02ca0.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('dkh', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}              # [unix]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - cmake
    - ninja
    # - llvm-openmp                                    # [osx]

test:
  commands:
    - ls -l $PREFIX/lib                                         # [unix]
    - ls -l $PREFIX/share/cmake/dkh                             # [unix]
    - dir "%PREFIX%\Library"                                    # [win]
    - dir "%PREFIX%"\Library\include                            # [win]
    # Verify library
    - test -f $PREFIX/lib/libdkh$SHLIB_EXT                      # [unix]
    - test ! -f $PREFIX/lib/libdkh.a                            # [unix]
    - if not exist %PREFIX%\\Library\\lib\\libdkh.dll.a exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\libdkh.dll exit 1    # [win]
    - if exist %PREFIX%\\Library\\lib\\libdkh.a exit 1          # [win]
    # Verify accessories
    - test -e $PREFIX/include/DKH/DKH_MANGLE.h                  # [unix]
    - if not exist %PREFIX%\\Library\\include\\DKH\\DKH_MANGLE.h exit 1  # [win]
    - test -e $PREFIX/share/cmake/dkh/dkhConfig.cmake           # [unix]
    - if not exist %PREFIX%\\Library\\share\\cmake\\dkh\\dkhConfig.cmake exit 1  # [win]
    # Inspect linkage
    - ldd -v $PREFIX/lib/libdkh$SHLIB_EXT                       # [linux and build_platform == target_platform]
    - otool -L $PREFIX/lib/libdkh$SHLIB_EXT                     # [osx]

about:
  home: http://www.reiher.ethz.ch/software/dkh-x2c.html
  dev_url: https://github.com/psi4/dkh
  license: LGPL-3.0-only
  license_url: https://opensource.org/license/lgpl-3-0/
  license_file:
    - COPYING
    - COPYING.LESSER
  license_family: LGPL
  summary: "Wolf, Reiher, and Hess's Douglas-Kroll-Hess (DKH) relativistic correction"

extra:
  recipe-maintainers:
    - loriab

