{% set name = "rathole" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rapiz1/rathole/archive/v{{ version }}.tar.gz
  sha256: 70e88a17354880c1cc26779d4ece4c565e86c65c1b55b2863c5050fce223242b

build:
  script:
    - cargo build --release
    - cargo install --path . --root "${PREFIX}"  # [unix]
    - cargo install --path . --root "%LIBRARY_PREFIX%"  # [win]
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - openssl
    - cargo-bundle-licenses

test:
  commands:
    - rathole --version

about:
  home: https://github.com/rapiz1/rathole
  summary: A secure, stable and high-performance reverse proxy for NAT traversal, written in Rust
  description: |
    rathole, like frp and ngrok, can help to expose the service on the device behind the NAT
    to the Internet, via a server with a public IP.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://github.com/rapiz1/rathole/tree/main/docs
  dev_url: https://github.com/rapiz1/rathole

extra:
  recipe-maintainers:
    - sshockwave
