boost:
    - 1.75.*
numpy:
#    - 1.19.*         # [python_impl == 'pypy']
    - 1.20.*         # [python_impl == 'pypy']    
python:
#    - 3.7.* *_cpython
#    - 3.8.* *_cpython
    - 3.9.* *_cpython
#    - 3.10.* *_cpython    
scotch:
    - 6.0.9
cross_compiler_target_platform:  # [win]
  - win-64                     # [win]
c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2017                     # [win]
c_compiler_version:            # [unix]
  - 8                          # [linux]
  #- 9                          # [linux]  
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2017                     # [win]
cxx_compiler_version:          # [unix]
  - 8                          # [linux]
  #- 9                          # [linux]
fortran_compiler:              # [unix or win64]
  - gfortran                   # [linux64 or (osx and x86_64)]
  - gfortran                   # [aarch64 or ppc64le or armv7l or s390x]
  - flang                      # [win64]
fortran_compiler_version:      # [unix or win64]
  - 8                          # [linux]
  #- 9                          # [linux]  