{% set name = "django-fernet-fields" %}
{% set version = "0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-fernet-fields-{{ version }}.tar.gz
  sha256: 7f7e03c86d9473a42031ebade2b15be1484aad18ef5576ddab156c4667e04c4a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip >=2.7
    - python
  run:
    - cryptography >=0.9
    - django >=1.11
    - python >=2.7

test:
  imports:
    - fernet_fields
    - fernet_fields.test
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/orcasgit/django-fernet-fields/
  summary: Fernet-encrypted model fields for Django
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - MichelML
