{% set name = "jupyterlite-core" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlite_core-{{ version }}.tar.gz
  sha256: fea7ffe880f6efb16cd39855dd459ec3cf87b238de076dae518033926af1150a

build:
  skip: true  # [py<38]
  entry_points:
    - jupyter-lite = jupyterlite_core.app:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - hatchling >=1.6.3,<2
    - pip
  run:
    - python
    - doit >=0.34,<1
    - importlib-metadata >=3.6  # [py<310]
    - jupyter_core >=4.7

test:
  imports:
    - jupyterlite_core
  commands:
    - pip check
    - jupyter-lite --help
  requires:
    - pip

about:
  home: https://github.com/jupyterlite/jupyterlite
  summary: Tools for building JupyterLite sites
  doc_url: https://jupyterlite.readthedocs.io
  dev_url: https://github.com/jupyterlite/jupyterlite
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - jtpio
    - martinRenou
