{% set name = "libuwebsockets" %}
{% set version = "20.35.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/uNetworking/uWebSockets/archive/refs/tags/v{{ version }}.tar.gz
    sha256: c52c98b7ff2c24534c17ad97d5fea8ca0cb7ff38cc933b8d08bac6e498a2ea6b

build:
  number: 0
  # uwebsockets is a header-only library that uses uwebsockets, so any user of it eventually links libusockets
  run_exports:
    - {{ pin_subpackage('libusockets', max_pin='x.x.x') }}
    
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - usockets

test:
  commands:
    - test -f $PREFIX/include/WebSockets/uWebSockets/App.h  # [unix]
    - if not exist %LIBRARY_INC%\\uWebSockets\App.h exit 1  # [win]

about:
  home: https://github.com/uNetworking/uSockets
  license: Apache-2.0
  license_file: LICENSE
  summary:  Miniscule cross-platform eventing, networking & crypto for async applications.

extra:
  recipe-maintainers:
    - traversaro
