{% set name = "caped-ai-metrics" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/caped-ai-metrics-{{ version }}.tar.gz
  sha256: 428947621a80b62acc7870965235538a29a77f93f5960ae0654c648989ae1c72

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - caped_ai_metrics
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/caped-ai-metrics/
  summary: Metric computation toolkit for segmentation and classification tasks
  license: ''
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - goanpeca
