{% set name = "data-morph-ai" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cfa23d793d3c6f9f1772670b763051950a7ab4e0c0fd346fbc2c8c69db3960fc


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - matplotlib >=3.3
    - numpy >=1.20
    - pandas >=1.2
    - pytweening >=1.0.5
    - scipy >=1.10.0
    - tqdm >=4.64.1

test:
  imports:
    - data_morph
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pip check
    - data-morph --version
    - pytest tests

about:
  home: https://github.com/stefmolin/data-morph
  summary: 'Teaching tool on the importance of data visualization.'
  description: |
    Data Morph transforms an input dataset of 2D points into select shapes,
    while preserving the summary statistics to a given number of decimal
    points through simulated annealing.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://stefmolin.github.io/data-morph/
  dev_url: https://github.com/stefmolin/data-morph

extra:
  recipe-maintainers:
    - stefmolin
