{% set name = "scenepic" %}
{% set version = "1.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 19933718fe6a387cdfc9c7341ecf99b532717fe8102c4dab033aad2a84661786


build:
  number: 0
  script: |
    set CMAKE_GENERATOR="MinGW Makefiles"  # [win]
    {{ PYTHON }} -m pip install . -vv


requirements:
  build:
    - cmake
    - ninja
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.16.2
    - pillow >=5.2.0
    - scipy >=1.4.1

test:
  imports:
    - scenepic
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://microsoft.github.io/scenepic/
  summary: 'Powerful, easy to use, and portable visualization toolkit for mixed 3D and 2D content'

  description: |
    ScenePic was created for 3D computer vision researchers such as those in Mixed Reality, 
    designed as to be a lightweight, reuseable 3D visualization library.
  license: MIT
  license_family: MIT
  license_file: LICENSE


  doc_url: https://microsoft.github.io/scenepic/
  dev_url: https://github.com/microsoft/scenepic

extra:
  recipe-maintainers:
    - jnyfah
