{% set name = "scenepic" %}
{% set version = "1.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 19933718fe6a387cdfc9c7341ecf99b532717fe8102c4dab033aad2a84661786


build:
  script: python setup.py install
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.16.2
    - pillow >=5.2.0
    - scipy >=1.4.1
    - cmake
  run:
    - python
    - numpy >=1.16.2
    - pillow >=5.2.0
    - scipy >=1.4.1

test:
  imports:
    - scenepic

about:
  home: https://github.com/<username>/scenepic
  license: MIT
  summary: "Lightweight, reusable 3D visualization library"
  description: |
    All platforms have good support for 2D images, with well-recognized formats
    such as PNG and JPEG that can be viewed out of the box (no installation)
    and shared trivially.
    However, while many formats exist for 3D data, none are well-supported
    without installation of tools such as MeshLab, Blender, etc.
    ScenePic was created for 3D computer vision researchers such as those
    working on [HoloLens](https://www.microsoft.com/en-gb/hololens)
    and [Mesh](https://www.microsoft.com/en-us/mesh) at Microsoft.
    It was designed to be a lightweight, reuseable 3D visualization
    library, with the following desiderata in mind:
    - Make experimentation with 3D data near effortless
    - Incredibly easy to create and share 3D results
      * zero-install sharing of detailed 3D results using HTML
      * based on modern web standards so usable with any modern browser
        (tested in Edge, FireFox and Chrome)
      * embeddable in other HTML documents
    - Performant
      * based on WebGL
    - High quality visuals
    - Works both offline or interactively in client-server setup
    - Simple, clean API
      * friendly Python front-end
      * basic mesh json file format
      * other language front ends easy to add
  dev_url: https://github.com/<username>/scenepic/issues


extra:
  recipe-maintainers:
    - jnyfah
    
