{% set name = "scenepic" %}
{% set version = "1.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/scenepic/archive/refs/tags/v1.0.18.tar.gz
  sha256: 2566e1fe839c61b3ed427931e0151cb07bed9468d1ccca74f3cb6be2a35aa1dd

build:
  skip: true  # [py>=400 or py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=42
    - wheel
    - cmake >=3.15
    - pip
  run:
    - python
    - numpy >=1.16.2
    - pillow >=5.2.0
    - scipy >=1.4.1

test:
  imports:
    - scenepic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://microsoft.github.io/scenepic/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jnyfah
    
