{% set name = "abi-dumper" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lvc/abi-dumper/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8a9858c91b4e9222c89b676d59422053ad560fa005a39443053568049bd4d27e

build:
  number: 0
  skip: true  # [win]
  script:
    - make install prefix=$PREFIX

requirements:
  build:
    - make
  host:
    - perl >=5.8
  run:
    - perl >=5.8
    - elfutils
    - vtable-dumper >=1.1
    - binutils
    - universal-ctags

test:
  commands:
    - abi-dumper --help

about:
  home: https://github.com/lvc/abi-dumper
  summary: 'Dump ABI of an ELF object containing DWARF debug info'
  description: >
    ABI Dumper — a tool to dump ABI of an ELF object containing DWARF debug info.

    The tool is intended to be used with ABI Compliance Checker tool for
    tracking ABI changes of a C/C++ library or kernel module:
    https://github.com/lvc/abi-compliance-checker

    The tool is developed by Andrey Ponomarenko.
  license: GLPL-2.1
  license_file: LICENSE
  dev_url: https://github.com/lvc/abi-dumper

extra:
  recipe-maintainers:
    - carterbox
