{% set name = "cascade" %}
{% set version = "0.1.1" %}
{% set sha256 = "852466c9f97126abd67fd5ed91512895f0bc98ac5d958577e3ae108755a5d5eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/esa/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - cmake >=3.18
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - ninja
  host:
    - python
    - pybind11 >=2.10
    - pybind11-abi
    - tbb
    - tbb-devel
    - boost-cpp >=1.73
    - fmt
    - heyoka >=0.21.0
    - heyoka.py >=0.21.0
    - spdlog
    - xtensor
    - xtensor-blas
    - hdf5

  run:
    - python
    - tbb
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
    - numpy
    - fmt
    - heyoka >=0.21.0
    - heyoka.py >=0.21.0
    - spdlog
    - xtensor
    - xtensor-blas
    - hdf5
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    

about:
  home: https://esa.github.io/cascade/
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: N-body simulation for the evolution of orbital environments

extra:
  recipe-maintainers:
    - darioizzo
    - bluescarni
