{% set name = "cascade" %}
{% set version = "0.1.1" %}
{% set sha256 = "1b73a287a1c7237aec5563d898060158229324724c1df7b51adf231a22756148" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/esa/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - cmake >=3.18
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - ninja
  host:
    - python
    - pybind11 >=2.10
    - pybind11-abi
    - tbb-devel
    - tbb
    - boost-cpp >=1.73
    - fmt
    - heyoka >=0.21.0
    - heyoka.py >=0.21.0
    - spdlog
    - xtensor
    - xtensor-blas
    - hdf5

  run:
    - python


about:
  home: https://esa.github.io/cascade/
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: N-body simulation for the evolution of orbital environments

extra:
  recipe-maintainers:
    - darioizzo
    - bluescarni