{% set name = "dclab" %}
{% set version = "0.43.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: true  # [py<38]
  entry_points:
    - dclab-compress = dclab.cli:compress
    - dclab-condense = dclab.cli:condense
    - dclab-join = dclab.cli:join
    - dclab-repack = dclab.cli:repack
    - dclab-split = dclab.cli:split
    - dclab-tdms2rtdc = dclab.cli:tdms2rtdc [tdms]
    - dclab-verify-dataset = dclab.cli:verify_dataset
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dclab-{{ version }}.tar.gz
  sha256: 6934b98418b946865d6c899838a393baa46592e4656f563a6cdf6305f78cbaa2

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - h5py >=3.0.0
    - hdf5plugin >=3.3.1
    - numpy >=1.21
    - python
    - scipy >=1.8.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - dclab
  commands:
    - pip list
    - pip check
    - dclab-compress --help
    - dclab-condense --help
    - dclab-join --help
    - dclab-repack --help
    - dclab-split --help
    - dclab-tdms2rtdc --help
    - dclab-verify-dataset --help
  requires:
    - pip

about:
  home: https://github.com/ZELLMECHANIK-DRESDEN/dclab
  summary: Library for real-time deformability cytometry (RT-DC)
  license: GPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
