{% set name = "mamonca" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/samwaseda/mamonca/archive/refs/heads/master.tar.gz
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mamonca-{{ version }}.tar.gz
  # sha256: b27fa27df87c3e90d16ddaeaeb1bc0426b1874feec88e4bcf2112e30f19be191
  sha256: b2005a71dc0aa880f46e9f0f663ccf4742edd7464b77b64d84b0c083e0d86cb0

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - cython
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - mc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/samwaseda/mamonca
  summary: mamonca - an integrated development environment (IDE) for computational materials science.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - samwaseda
    - jan-janssen
