{% set name = "libbayes-filters-lib" %}
{% set version = "0.10.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/robotology/bayes-filters-lib/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 10c7cc1f0c7fd73153c9a65052977cb8bddcb3725c819a307b91f082a5621384

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - eigen

test:
  commands:
    - test -f $PREFIX/include/BayesFilters/GaussianFilter.h  # [unix]
    - test -f $PREFIX/lib/libBayesFilters${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\\BayesFilters\\GaussianFilter.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\BayesFilters.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\BayesFilters.dll exit 1  # [win]

about:
  home: https://github.com/robotology/bayes-filters-lib
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: A flexible, modern, C++ recursive Bayesian estimation library.

extra:
  feedstock-name: bayes-filters-lib
  recipe-maintainers:
    - traversaro
