{% set name = "sirius" %}
{% set version = "5.6.4" %}

package:
  name: {{ name|lower }}-ms
  version: {{ version }}

source:
  - url: https://github.com/boecker-lab/sirius/releases/download/v{{ version }}-SNAPSHOT/{{ name }}-{{ version }}-SNAPSHOT-linux64.zip  # [linux]
    sha256: 1852e6c55a1960ec6cdef6c5d66cf8386297dc7b2896bfa1afdffc03fb9420c1  # [linux]
  - url: https://github.com/boecker-lab/sirius/releases/download/v{{ version }}-SNAPSHOT/{{ name }}-{{ version }}-SNAPSHOT-osx64.zip  # [osx]
    sha256: baf1f878f887b29306eb388e7a557ae247b35004536cebc79c3754aececc6595  # [osx]
  - url: https://github.com/boecker-lab/sirius/releases/download/v{{ version }}-SNAPSHOT/{{ name }}-{{ version }}-SNAPSHOT-win64.zip  # [win]
    sha256: 3bde63f5da5ca0abd6d85ec26b45ee8abb030a1849fe2b1928ed088e82458131  # [win]

build:
  number: 0

requirements:
  host:
    - openjdk
    - coin-or-cbc # [not win]
    - bzip2
    - zlib
  run:
    - openjdk
    - coin-or-cbc # [not win]
    - bzip2
    - zlib

test:
  requires:
    - wget  # [not win]

about:
  home: https://bio.informatik.uni-jena.de/software/sirius/
  license: AGPL-3.0-only
  license_file:
    - COPYING.txt  # [not osx]
    - LICENSE.txt  # [not osx]
    - Contents/Resources/COPYING.txt  # [osx]
    - Contents/Resources/LICENSE.txt  # [osx]
  summary: "SIRIUS (CLI + GUI) LC-MS/MS data analyses framework. Includes: SIRIUS, ZODIAC, CSI:FingerID (with COSMIC) and CANOPUS"
  description: SIRIUS is a java-based software framework for the analysis of LC-MS/MS data of metabolites and other
    small molecules of biological interest. SIRIUS integrates a collection of our tools, including CSI:FingerID
    (with COSMIC), ZODIAC and CANOPUS.  In particular, both the graphical user interface and the command line version
    of SIRIUS seamlessly integrate the CSI:FingerID and CANOPUS web services.
  doc_url: https://boecker-lab.github.io/docs.sirius.github.io/
  dev_url: https://github.com/boecker-lab/sirius

extra:
  recipe-maintainers:
    - mfleisch
