{% set name = "sirius" %}
{% set version = "5.6.4" %}

package:
  name: {{ name|lower }}-ms
  version: {{ version }}

source:
  - url: https://github.com/boecker-lab/sirius/releases/download/v{{ version }}-SNAPSHOT/{{ name }}-{{ version }}-SNAPSHOT-linux64.zip  # [linux]
    sha256: 0a1a5ec057bd61418e52ff29a0048fd8cf8a57f52925aea5e43a9616869ff49f  # [linux]
  - url: https://github.com/boecker-lab/sirius/releases/download/v{{ version }}-SNAPSHOT/{{ name }}-{{ version }}-SNAPSHOT-osx64.zip  # [osx]
    sha256: 8a5efbf409ddeb4e8b76b5c790e2dea8aa6fd6c0db603481ac53c314da82678c  # [osx]
  - url: https://github.com/boecker-lab/sirius/releases/download/v{{ version }}-SNAPSHOT/{{ name }}-{{ version }}-SNAPSHOT-win64.zip  # [win]
    sha256: b5cd69993f4c5d91adf3b7d6ff68611e8eba1907c66bad837d3c32dd74330661  # [win]

build:
  number: 0

requirements:
  host:
    - openjdk
    - coin-or-cbc # [not win]
    - bzip2
    - zlib
  run:
    - openjdk
    - coin-or-cbc # [not win]
    - bzip2
    - zlib

test:
  requires:
    - wget  # [not win]

about:
  home: https://bio.informatik.uni-jena.de/software/sirius/
  license: AGPL-3.0-only
  license_file:
    - COPYING.txt  # [not osx]
    - LICENSE.txt  # [not osx]
    - Contents/Resources/COPYING.txt  # [osx]
    - Contents/Resources/LICENSE.txt  # [osx]
  summary: "SIRIUS (CLI + GUI) LC-MS/MS data analyses framework. Includes: SIRIUS, ZODIAC, CSI:FingerID (with COSMIC) and CANOPUS"
  description: SIRIUS is a java-based software framework for the analysis of LC-MS/MS data of metabolites and other
    small molecules of biological interest. SIRIUS integrates a collection of our tools, including CSI:FingerID
    (with COSMIC), ZODIAC and CANOPUS.  In particular, both the graphical user interface and the command line version
    of SIRIUS seamlessly integrate the CSI:FingerID and CANOPUS web services.
  doc_url: https://boecker-lab.github.io/docs.sirius.github.io/
  dev_url: https://github.com/boecker-lab/sirius

extra:
  recipe-maintainers:
    - mfleisch
