{% set name = "sirius" %}
{% set version = "4.9.8" %}

package:
  name: {{ name|lower }}-ms
  version: {{ version }}

source:
  - url: https://github.com/boecker-lab/sirius/releases/download/v{{ version }}/{{ name }}-{{ version }}-linux64.zip  # [linux]
    sha256: 0312915249181df975a23b605608b69badd4a657236a8bb7a0aa174a840ddc56  # [linux]
  - url: https://github.com/boecker-lab/sirius/releases/download/v{{ version }}/{{ name }}-{{ version }}-osx64.zip  # [osx]
    sha256: ed9e853974feb942b6833c5ce0685c9307f074bc6519a4428c45c11859ae508f  # [osx]
  - url: https://github.com/boecker-lab/sirius/releases/download/v{{ version }}/{{ name }}-{{ version }}-win64.zip  # [win]
    sha256: e4a4b83e361ad50a2562acbe4b2aa0593f1d032b2bb6696a8163ef76ba837bff  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
  run:
    - zlib

test:
  requires:
    - wget  # [not win]

about:
  home: https://bio.informatik.uni-jena.de/software/sirius/
  license: AGPL-3.0-only
  license_file:
    - COPYING.txt  # [not osx]
    - LICENSE.txt  # [not osx]
    - Contents/COPYING.txt  # [osx]
    - Contents/LICENSE.txt  # [osx]
  summary: "SIRIUS (CLI + GUI) LC-MS/MS data analyses framework. Includes: SIRIUS, ZODIAC, CSI:FingerID (with COSMIC) and CANOPUS"
  description: SIRIUS is a java-based software framework for the analysis of LC-MS/MS data of metabolites and other
    small molecules of biological interest. SIRIUS integrates a collection of our tools, including CSI:FingerID
    (with COSMIC), ZODIAC and CANOPUS.  In particular, both the graphical user interface and the command line version
    of SIRIUS seamlessly integrate the CSI:FingerID and CANOPUS web services.
  doc_url: https://boecker-lab.github.io/docs.sirius.github.io/
  dev_url: https://github.com/boecker-lab/sirius

extra:
  recipe-maintainers:
    - mfleisch
