{% set name = "dominodatalab" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dominodatalab-{{ version }}.tar.gz
  sha256: 078e6ef8270a1e999973723287d40ea810f132dd94d8a80862f4a1ca199e529b

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - packaging
    - requests >=2.4.2
    - bs4 ==0.*,>=0.0.1
    - polling2 >=0.5.0,<0.6.dev0
    - urllib3 >=1.26.12,<1.27.dev0
    - typing-extensions >=4.4.0,<4.5.dev0
    - frozendict >=2.3.4,<2.4.dev0
    - python-dateutil >=2.8.2,<2.9.dev0

test:
  imports:
    - domino
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dominodatalab/python-domino
  summary: Python bindings for the Domino API
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - janjagusch
