{% set version = '0.8.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-adherer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/AdhereR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/AdhereR/AdhereR_{{ version }}.tar.gz
  sha256: e26dc4c8c4a5bd92a0f6da853fdf2bd25b9a0589df17640764603c5dc5f7282d

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-data.table >=1.9
    - r-jpeg >=0.1
    - r-lubridate >=1.5
    - r-png >=0.1
    - r-rsvg >=1.3
    - r-webp >=1.0
  run:
    - r-base
    - r-data.table >=1.9
    - r-jpeg >=0.1
    - r-lubridate >=1.5
    - r-png >=0.1
    - r-rsvg >=1.3
    - r-webp >=1.0

test:
  commands:
    - $R -e "library('AdhereR')"           # [not win]
    - "\"%R%\" -e \"library('AdhereR')\""  # [win]

about:
  home: https://github.com/ddediu/AdhereR
  license: GPL-2.0-or-later
  summary: Computation of adherence to medications from Electronic Health care Data and visualization
    of individual medication histories and adherence patterns. The package implements
    a set of S3 classes and functions consistent with current adherence guidelines and
    definitions. It allows the computation of different measures of adherence (as defined
    in the literature, but also several original ones), their publication-quality plotting,
    the estimation of event duration and time to initiation, the interactive exploration
    of patient medication history and the real-time estimation of adherence given various
    parameter settings. It scales from very small datasets stored in flat CSV files
    to very large databases and from single-thread processing on mid-range consumer
    laptops to parallel processing on large heterogeneous computing clusters. It exposes
    a standardized interface allowing it to be used from other programming languages
    and platforms, such as Python.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
	- Ariel Balter <ariel@arielbalter.com>

