{% set version = "0.9" %}
{% set name = "r-sirius-ms" %}
{% set commit = "027828d27624b94f0d99885eee2ae45301a9b9fb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/boecker-lab/sirius-client-openAPI/archive/{{ commit }}.zip
  sha256: 404cd1d1a9eb660407128548db4da2cda0b37d2115db260402d82cad33ab45d4

build:
  noarch: generic
  number: 0

requirements:
  build:
    - r-base >=3.5.0
    - r-jsonlite
    - r-httr2
    - r-r6
    - r-base64enc
    - r-stringr
  run:
    - r-base >=3.5.0
    - r-jsonlite
    - r-httr2
    - r-r6
    - r-base64enc
    - r-stringr
    - sirius-ms

test:
  commands:
    - sh run_test.sh           # [not win]
    - call run_test.bat        # [win]

about:
  home: https://github.com/boecker-lab/sirius-client-openAPI/tree/master/client-api_r
  summary: 'RSirius: R library for SIRIUS MS/MS analyses software.'
  description: |
    R client for the SIRIUS (local) REST API (OpenAPI) that provides the full functionality of the SIRIUS 
    MS/MS analyses software including its web based features as background service.
  license: Apache-2.0
  license_file: client-api_r/LICENSE.txt
  doc_url: https://boecker-lab.github.io/docs.sirius.github.io/
  dev_url: https://github.com/boecker-lab/sirius-client-openAPI/tree/master/client-api_r

extra:
  recipe-maintainers:
    - mfleisch
    - joXemMx
