{% set version = "1.0.0" %}
{% set name = "r-sirius-ms" %}
{% set commit = "d9e461aee1c188f44f5b68f1e7d824c2d825808e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/boecker-lab/sirius-client-openAPI/archive/{{ commit }}.zip
  sha256: 84defdc1f5a3d02ae76bcf1e05c9c668518676a2b90085d3b372e66e18448bb2

build:
  noarch: generic
  number: 0

requirements:
  build:
    - r-base >=3.5.0
    - r-jsonlite
    - r-httr2
    - r-r6
    - r-base64enc
    - r-stringr
  run:
    - r-base >=3.5.0
    - r-jsonlite
    - r-httr2
    - r-r6
    - r-base64enc
    - r-stringr
    - sirius-ms

test:
  commands:
    - sh run_test.sh           # [not win]
    - call run_test.bat        # [win]

about:
  home: https://github.com/boecker-lab/sirius-client-openAPI/tree/master/client-api_r
  summary: 'RSirius: R library for SIRIUS MS/MS analyses software.'
  description: |
    R client for the SIRIUS (local) REST API (OpenAPI) that provides the full functionality of the SIRIUS 
    MS/MS analyses software including its web based features as background service.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://boecker-lab.github.io/docs.sirius.github.io/
  dev_url: https://github.com/boecker-lab/sirius

extra:
  recipe-maintainers:
    - mfleisch
