{% set name = "modelparameters" %}
{% set version = "2022.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: dd8bc654a483dbe984b0dac4ded9370874f7dd5cf2a2ad58b04130c17a00386b

build:
  number: 0
  noarch: python
  script: python -m pip install -v --no-deps .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - mpmath
    - numpy
    - pintls

test:
  imports:
    - modelparameters

  commands:
    - pip check

about:
  home: https://github.com/ComputationalPhysiology/modelparameters
  summary: A module providing parameter structure for physical modeling
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  doc_url: https://computationalphysiology.github.io/modelparameters/
  dev_url: https://github.com/ComputationalPhysiology/modelparameters

extra:
  recipe-maintainers:
    - finsberg
