
{% set name = "conda-oci-mirror" %}
{% set version = "0.1.0.2023.2.8" %}
{% set commit = "018eebd010725eaaf891fbf6cd8438fb1e638b48" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/channel-mirrors/conda-oci-mirror/archive/{{ commit }}.tar.gz
  sha256: 0fbeb8a9c4f7d33f26e8b927cbb2f4c707e341c4c3d01c296af61a9bdd7e1fa9


build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click
    - build
    - requests
    - oras-py 0.1.14
    - conda-package-handling

test:
  imports:
    - conda_oci_mirror
    - conda_oci_mirror.mirror
    - conda_oci_mirror.repo
  requires:
    - pip
  commands:
    - pip check
    - conda-oci --help

about:
  home: https://github.com/channel-mirrors/conda-oci-mirror
  summary: 'Tools to mirror conda packages to an OCI registry'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaimergp
    - wolfv
