{% set name = "iscd-advection" %}
{% set version = "1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url: https://github.com/ISCDtoolbox/Advection/archive/refs/heads/master.zip
  sha256: e8688d5e1c5d704340ccecf1ad40f46b05b752888f00db43540f9fd55405d786

build:
  number: 0
  skip: true  # [py2k]  

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake
    - make  # [not win]
    - jom  # [win]    
    - iscd-commons
  run:
    - iscd-commons

about:
  home: https://iscd.sorbonne-universite.fr/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'ISCD - Advection'
  description: |
    Advect is a program for solving linear advection problems in two and three dimensions.
  doc_url: https://github.com/ISCDtoolbox/Advection/tree/master/Documentation
  dev_url: https://github.com/ISCDtoolbox/Advection 

extra:
  recipe-maintainers:
    - ldallolio
