{% set name = "PyPythia" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tschuelia/PyPythia/archive/{{ version }}.tar.gz
  sha256: f231feee14cc21a387782a58340adc3e45ddd5d375e40ee070f597201397f69e

build:
  skip: true  # [win]
  skip: true  # [py<37]
  entry_points:
    - pythia = pypythia.prediction:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - pandas
    - biopython
    - scikit-learn >=1.0
    - lightgbm >=3.3

test:
  imports:
    - pypythia
  commands:
    - pip check
    - pythia --help
  requires:
    - pip

about:
  home: https://github.com/tschuelia/PyPythia
  summary: Lightweight python library for predicting the difficulty of alignments in phylogenetics
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschuelia
