cross_compiler_target_platform:  # [win]
  - win-64                     # [win]
c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2017                     # [win]
c_compiler_version:            # [unix]
  - 8                          # [linux]
  #- 9                          # [linux]  
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2017                     # [win]
cxx_compiler_version:          # [unix]
  - 8                          # [linux]
  #- 9                          # [linux]
fortran_compiler:              # [unix or win64]
  - gfortran                   # [linux64 or (osx and x86_64)]
  - gfortran                   # [aarch64 or ppc64le or armv7l or s390x]
  - flang                      # [win64]
fortran_compiler_version:      # [unix or win64]
  - 8                          # [linux]
  #- 9                          # [linux]  

# dual build configuration
channel_sources:
  - conda-forge,defaults                        # [not (aarch64 or armv7l or (osx and arm64) or s390x)]
  - conda-forge/label/rust_dev,conda-forge      # [osx and arm64]
  - conda-forge                                 # [aarch64]
  - conda-forge,c4armv7l,defaults               # [armv7l]
  - https://conda-web.anaconda.org/conda-forge  # [s390x]

channel_targets:
  - conda-forge main
