{% set name = "iscd-commons" %}
{% set version = "1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url: https://github.com/ISCDtoolbox/Commons/archive/refs/heads/master.zip
  sha256: 02fae58388a93692f3c73dcb4619bbcf838b479744cf6972edeca330f756125a

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
#    - openlibm
  host:
    - cmake
    - make [not win]
    - nmake [win]

about:
  home: https://iscd.sorbonne-universite.fr/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'ISCD - Commons library'
  description: |
    Common codes used for ISCD softwares (Linear algebra, Chrono, I/O...)
  doc_url: https://github.com/ISCDtoolbox/Commons/blob/master/README.md
  dev_url: https://github.com/ISCDtoolbox/Commons 

extra:
  recipe-maintainers:
    - felipebordeu
    - ldallolio
