{% set name = "iscd-commons" %}
{% set version = "0.0.0rc0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ISCDtoolbox/Commons/archive/57f0b0ed46d45a12fa60c42bce2c6fa73c84bc30.zip
  sha256: 065bdadc9011c3830296f019e2e3b60743939f529f3ba2e8e586fba9d239e03a

build:
  number: 0
  skip: true  # [py2k or win] # Cannot open include file: 'pthread.h': No such file or directory

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake
    - make  # [not win]
    - jom  # [win]

test:
  commands:
    - test -f $PREFIX/lib/libCommons.so  # [linux]
    - test -f $PREFIX/lib/libCommons.dylib  # [osx]

about:
  home: https://iscd.sorbonne-universite.fr/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'ISCD - Commons library'
  description: |
    Common codes used for ISCD softwares (Linear algebra, Chrono, I/O...)
  doc_url: https://github.com/ISCDtoolbox/Commons/blob/master/README.md
  dev_url: https://github.com/ISCDtoolbox/Commons 

extra:
  recipe-maintainers:
    - ldallolio
    - cnrdn
    - fbordeu