{% set name = "zppy" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/zppy/archive/v{{ version }}.tar.gz
  sha256: a233512d612bef036f022b40c9b469eb6d28f6cfcf8f16ebf6dcae946df49d0a

build:
  entry_points:
    - zppy=zppy.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - configobj
    - jinja2

test:
  imports:
    - zppy
  commands:
    - pip check
    - zppy --help
  requires:
    - pip

about:
  home: https://github.com/E3SM-Project/zppy
  summary: 'E3SM post-processing toolchain'
  license: BSD-3-Clause AND Unlicense
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - mahf708
    - xylar
    - tomvothecoder
    - forsyth2
    - chengzhuzhang
