{% set name = "aioshutil" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aioshutil-{{ version }}.tar.gz
  sha256: ddabe1748c8a71ec3c7d213a4d0cf58fb495c71419334a0575b1f8a3be8373e8

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools-scm
    - pip
  run:
    - python
    - typing-extensions  # [py<310]

test:
  imports:
    - aioshutil
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kumaraditya303/aioshutil
  summary: Asynchronous shutil module.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ivergara
