{% set name = "oneworld" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01fb5e76db5781b298225a32ca7ed36d5789fa423a7416d9abfd50a952d8a870

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >= 3.10
    - pip
  run:
    - python >= 3.10
    - matplotlib >= 3.6.2
    - pandas >= 1.5.2
    - seaborn >= 0.12.2
    - jinja2 >= 3.1.2
    - cartopy >= 0.21.1

test:
  imports:
    - oneworld
  requires:
    - pytest
  source_files:
    - tests
    - tests_data

about:
  home: https://bitbucket.org/taguilar/oneworld
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python mapping made easy'
  description: |
    OneWorld is a python mapping library intended to make plotting maps 
    with python easy and accessible to everyone. It combines the mapping 
    power of cartopy with the versatility of leaflet and the aesthetics 
    and input structure of seaborn to create both static and interactive maps.
  doc_url: https://oneworld.readthedocs.io
  dev_url: https://bitbucket.org/taguilar/oneworld

extra:
  recipe-maintainers:
    - taguilar
