{% set name = "graphormer_pretrained" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graphormer_pretrained-{{ version }}.tar.gz
  sha256: da512327ab7680838d9839b8987d9476c330697489c6a9b3a34cfe71906f5502

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.8
    - setuptools
    - wheel
    - cython
    - numpy
    - pip
  run:
    - python >=3.8
    - tqdm
    - gcsfs
    - pytorch
    - torch-geometric
    - ogb
    - tensorboardx
    - fairseq
    - lmdb
    - datamol
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - graphormer_pretrained
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Packaging of Graphormer is a deep learning package by Microsoft that allows researchers and developers to train custom models for molecule modeling tasks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - maclandrol
