{% set name = "net-http-persistent" %}
{% set version = "4.0.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: 2752f4cce05fd1c45e0537c6f3a98fa5a4899efd5f88e63c104ed5f05cbddef9

build:
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
    - cp {{ name }}-*/LICENSE .
  skip: true  # [win]

requirements:
  host:
    - ruby <2.6, >=2.3
  run:
    - ruby <2.6, >=2.3

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'
    - rb-connection_pool >=2.2, <3

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Thread-safe persistent connections with Net::HTTP
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/drbrain/{{ name }}

extra:
  recipe-maintainers:
    - svengiegerich
    - janjagusch