package:
  name: recycle
  version: "6.0.0"

source:
  git_url: https://github.com/steinwurf/recycle.git
  git_tag: v{{ package.version }}


requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    
build:
  number: 0
  script: |
    mkdir build
    cd build
    cmake \
      -DCMAKE_INSTALL_PREFIX=$PREFIX \
      ..
    make -j${{ env.NUM_CPUS }}
    make install

test:
  commands:
    - test -e include/recycle/no_locking_policy.hpp
    - test -e include/recycle/shared_pool.hpp
    - test -e include/recycle/unique_pool.hpp

about:
  home: https://github.com/steinwurf/recycle
  summary: A simple C++ resource pool implementation
  description: recycle is an implementation of a simple C++ resource pool.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainer: DerThorsten