{% set name = "recycle" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/steinwurf/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 65d3d10442a0fda795ef99d32ed1e173c43e985dbd24b5b49e44487ea46ae35c

build:
  number: 0
  script: |
    mkdir build
    cd build
    cmake \
      -DCMAKE_INSTALL_PREFIX=$PREFIX \
      ..
    make -j${{ env.NUM_CPUS }}
    make install

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    
test:
  commands:
    - test -e include/recycle/no_locking_policy.hpp
    - test -e include/recycle/shared_pool.hpp
    - test -e include/recycle/unique_pool.hpp

about:
  home: https://github.com/steinwurf/recycle
  summary: A simple C++ resource pool implementation
  description: recycle is an implementation of a simple C++ resource pool.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers: 
    - DerThorsten
