{% set version = "1.0.3" %}

package:
  name: fmjpeg2koj
  version: {{ version }}

source:
  url: https://github.com/DraconPern/fmjpeg2koj/archive/refs/heads/master.zip
  sha256: f1f5214084ce0ffb489fd914f08ac05469bf4103c05c9ad7bd82b8c690082e0d
  patches:
    - 0001-Install-shared-library-in-Windows.patch
build:
  number: 0

requirements:
  build:
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - dcmtk
    - openjpeg
    - m2-patch  # [win]

test:
  commands:
    - test -f $PREFIX/include/fmjpeg2k/djdecode.h  # [unix]
    - if not exist %LIBRARY_INC%\\fmjpeg2k\\djdecode.h exit 1  # [win]
    - test -f $PREFIX/lib/libfmjpeg2k.so.1  # [linux]
    - test -f $PREFIX/lib/libfmjpeg2k.1.dylib  # [mac]
    - if not exist %LIBRARY_BIN%\\fmjpeg2k.dll exit 1  # [win]
    - test -f $PREFIX/lib/cmake/fmjpeg2k/fmjpeg2kConfig.cmake  # [unix]
    - dir %LIBRARY_PREFIX%\\lib\\cmake\\fmjpeg2k  # [win]
    - if not exist %LIBRARY_PREFIX%\\lib\\cmake\\fmjpeg2k\\fmjpeg2kConfig.cmake exit 1  # [win]


about:
  home: https://github.com/DraconPern/fmjpeg2koj
  license:  Apache-2.0
  license_file: LICENSE
  summary:  JPEG2000 codec for DCMTK using openjpeg 

extra:
  recipe-maintainers:
    - sameeul
