{% set name = "crepes" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b6f3db1ce6fc7146b1bd0b4ac3aea6a7fbb0b3ce720a632ea31c31642fe55741

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy
    - pandas
    - python >=3.8

test:
  imports:
    - crepes

about:
  home: "https://github.com/henrikbostrom/crepes"
  license: BSD
  license_family: BSD
  license_file: "https://github.com/henrikbostrom/crepes/blob/main/LICENSE"
  summary: "Conformal regressors and predictive systems (crepes)"
  doc_url: "https://crepes.readthedocs.io/en/latest/"
  dev_url: "https://github.com/henrikbostrom/crepes"

extra:
  recipe-maintainers:
    - henrikbostrom
