{% set name = "marching_cubes" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ilastik/marching_cubes/archive/{{ version }}.tar.gz
  sha256: e173ca9a79382ff21f25dad5094133ad524d0958de773d8ea129a431d0a242de

build:
  number: 0

requirements:
  build:
    - cmake
    - make  # [not win]
    - {{ compiler("cxx") }}
  host:
    - python
    - boost-cpp
    - pybind11
  run:
    - python
    - numpy >=1.12

test:
  imports:
    - marching_cubes

about:
  home: https://github.com/ilastik/marching_cubes
  summary: 'A fast marching cubes implementation in C++ with python bindings.'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/ilastik/marching_cubes

extra:
  recipe-maintainers:
    - k-dominik
