{% set name = "cuda-version" %}
{% set version = "12.0.0" %}
{% set major_version = version.split('.')[0]|int %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: true  # [osx]

requirements:
  run_constrained:
    - __cuda >={{ major_version }}

about:
  home: https://developer.nvidia.com/cuda-toolkit
  #license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: A meta-package for pinning to a CUDA release version
  description: |
    A meta-package for pinning to a CUDA release version
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - adibbley
