{% set version = "4.0.1" %}

package:
  name: qt6-advanced-docking-system
  version: {{ version }}

source:
  url: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/archive/{{ version }}.tar.gz
  sha256: c65357f630dc22b645b5dfa2684fb2748a347235267e952dc30986da9bf88f50
  patches:
    - 0001-CMakeLists.patch

build:
  number: 0
<<<<<<< HEAD:recipes/qt-advanced-docking-system/meta.yaml
  run_exports:
    - qt6-advanced-docking-system
  missing_dso_whitelist:
  # Follow: https://github.com/conda-forge/deno-feedstock/blob/49611827965b148b4e724b23d4077de17cf4f90b/recipe/meta.yaml#L13-L23
    - /System/Library/Frameworks/Metal.framework/Versions/A/Metal  # [osx]

build:
  number: 0
=======
  missing_dso_whitelist:
  # Follow: https://github.com/conda-forge/deno-feedstock/blob/49611827965b148b4e724b23d4077de17cf4f90b/recipe/meta.yaml#L13-L23
    - /System/Library/Frameworks/Metal.framework/Versions/A/Metal  # [osx]
>>>>>>> 993e5101cb (Fix macosX linking issue in the right recipe):recipes/qt6-ads/meta.yaml

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}          # [not osx]
    - make                           # [not win]
    - ninja                          # [win]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]

  host:
    - qt6-main
    - libxcb                         # [linux]
    
test:
  commands:
    - if not exist %LIBRARY_BIN%\\qtadvanceddocking.dll exit 1                                    # [win]
    - if not exist %LIBRARY_INC%\\qtadvanceddocking\\ads_globals.h exit 1                         # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\qtadvanceddocking\\qtadvanceddockingConfig.cmake exit 1  # [win]
    - test -f $PREFIX/lib/libqtadvanceddocking${SHLIB_EXT}                                        # [unix]
    - test -f $PREFIX/include/qtadvanceddocking/ads_globals.h                                     # [unix]
    - test -f $PREFIX/lib/cmake/qtadvanceddocking/qtadvanceddockingConfig.cmake                   # [unix]

about:
  home: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System
  license: LGPL-2.1-only
  license_file: gnu-lgpl-v2.1.md
  summary: Advanced Docking System for Qt

extra:
  recipe-maintainers:
    - n-elie
 
