{% set name = "flake8-to-ruff" %}
{% set version = "0.0.233" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8_to_ruff-{{ version }}.tar.gz
  sha256: ee519743260fa6d263415a5c5db90c44c3958fdc42069a5b249e7648c5ac3ac8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - maturin >=0.14,<0.15
    - pip    
    - rust
  run:
    - python >=3.7

test:
  imports:
    - flake8_to_ruff
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/charliermarsh/ruff#subdirectory=crates/flake8_to_ruff  
  summary: Convert existing Flake8 configuration to Ruff.
  license: MIT
  license_file: local_dependencies/ruff/LICENSE

extra:
  recipe-maintainers:
    - svengiegerich
