{% set name = "torchsnapshot" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchsnapshot-{{ version }}.tar.gz
  sha256: 618c4947ae500ee8750442fb5dc94f11899be2ddb6b829155c0948460cf94a4f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - aiofiles
    - aiohttp
    - importlib-metadata
    - nest-asyncio
    - psutil
    - python >=3.7
    - pyyaml
    - pytorch
    - typing-extensions

test:
  imports:
    - torchsnapshot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytorch/torchsnapshot
  summary: A performant, memory-efficient checkpointing library for PyTorch applications, designed with large, complex distributed workloads in mind.
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
