{% set name = "htmlgen" %}
{% set org = "srittau" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/python-{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 891ac5a30266d658a6d4e708e53f1c4a0621a36cbdbda4c4c4e9ac09a06ea863

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - h5glance = "{{ name }}.terminal:main"
    - h5glance-html = "{{ name }}.html_cli:main"

requirements:
  host:
    - python >=3.7
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7

test:
  requires:
    - pip
  imports:
    - {{ name }}
  commands:
    - pip check

about:
  home: https://github.com/{{ org }}/python-{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to generate HTML from classes.
  description: Library to generate HTML from classes.
  doc_url: https://github.com/{{ org }}/python-{{ name }}
  dev_url: https://github.com/{{ org }}/python-{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
