{% set name = "textx" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/textX-{{ version }}.tar.gz
  sha256: cd432adb82e348960cecdcabe68dbb916fe6eb2e4cb067c4a4b68b8c9ec51acf

build:
  entry_points:
    - textx = textx.cli:textx
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - arpeggio >=2.0.0
    - future
    - python >=3.6

test:
  source_files:
    - tests
  imports:
    - textx
  commands:
    - pip check
    - textx --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - click >=7.0,<8.0
    - pip
    - pytest

about:
  home: http://textx.github.io/textX/
  dev_url: https://github.com/textX/textX
  summary: Meta-language for DSL implementation inspired by Xtext
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
