{% set name = "watex" %}
{% set version = "0.1.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/WEgeophysics/{{name}}/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: db395f8543915b60360e49785343e5b98993b0bbcd4402f27ef065c74a94693a

build:
  number: 1
  noarch: python
  entry_points:
    - version= watex.cli:version
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - cython >=0.29.33
    - h5py >=3.2.0
    - joblib >=1.2.0
    - matplotlib ==3.5.2
    - missingno >=0.4.2
    - mlxtend >=0.21
    - numpy <=1.23.0
    - openpyxl >=3.0.3
    - pandas >=1.4.0
    - pyjanitor >=0.1.7
    - pyproj >=3.3.0
    - python >=3.9
    - pyyaml >=5.0.0
    - scikit-learn >=1.1.2
    - scipy >=1.9.0
    - seaborn >=0.12.0
    - setuptools
    - pytables >=3.6.1
    - threadpoolctl ==3.1.0
    - tqdm <=4.64.1
    - xgboost >=1.5.0
    - yellowbrick >=1.5.0

test:
  imports:
    - watex
    - watex._build
    - watex.analysis
    - watex.cases
    - watex.datasets
    - watex.datasets.data
    - watex.datasets.data.edis
    - watex.datasets.descr
    - watex.etc
    - watex.exlib
    - watex.externals
    - watex.externals._pkgs
    - watex.geology
    - watex.methods
    - watex.models
    - watex.utils
    - watex.view
  commands:
    - version --help
  requires:
    - pytest

about:
  home: "https://github.com/WEgeophysics/watex"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Machine learning research in water exploration"
  description: |
    watex is a Python library to solve real-engineering problems in  
    the field of groundwater exploration.It uses geophysical, hydrogeology,
    and geology methods to  minimize the  unsucessfull drillings, 
    unustainable boreholes and reduce the cost of the hydrogeology 
    parameter collections. 
  doc_url: "https://watex.readthedocs.io"
  dev_url: "https://github.com/WEgeophysics/watex"

extra:
  recipe-maintainers:
    - WEgeophysics
