{% set name = "mc-goods" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mc_goods-{{ version }}.tar.gz
  sha256: bbea9a785b23b93163178c6c6d43fe22937856059a91a264e05b8ac22323c877

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.6
    - intake
    - numpy
    - requests

test:
  imports:
    - mc_goods
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/axiom-data-science/mc-goods
  summary: model_catalogs catalogs for GOODS
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kthyng
