{% set name = "azure-purview-account" %}
{% set version = "1.0.0b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-purview-account-{{ version }}.zip
  sha256: d9a02494a62cfb5be2cf5de2b64becd23c5949cf05856d7dfe665256d5ba20ae

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - azure-core <2.0.0,>=1.16.0
    - msrest >=0.6.21
    - six >=1.11.0
    - azure-purview-nspkg  # [py<30]
    - typing  # [py<35]

test:
  imports:
    - azure.purview.account
    - azure.purview.account.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Purview Account Client Library for Python
  license: MIT
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - redur