{% set name = "dhall-python" %}
{% set version = "0.1.14" %}
{% set sha256 = "d6b95f03d25c80a39267891b6401be6af411e5eac44591a1654267a96533c06c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/s-zeng/dhall-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

# NOTE: ignore the makefile in the src repo since this calls maturin et all
# through poetry (eg "poetry run ...") which appears to make conda upset
build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - maturin build --release -i {{ PYTHON }}
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin >=0.14,<0.15
    - pip
    - make
  host:
    - python
    - pip
    - maturin >=0.14,<0.15
  run:
    - python
    - libgcc-ng              # [linux]
    - libgcc                 # [osx]

test:
  imports:
    - dhall
  commands:
    - pip check
    # - pytest tests
  requires:
    - pip
    # - hypothesis
    # - pytest

about:
  home: https://github.com/s-zeng/dhall-python
  summary: 'Python bindings for Dhall, a functional configuration language'
  description: |
    Dhall-python contains the Python bindings for Dhall, implemented in Rust.
  license: MIT
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - ndwarshuis
