{% set name = "dhall-python" %}
{% set version = "0.1.14" %}
{% set sha256 = "d6b95f03d25c80a39267891b6401be6af411e5eac44591a1654267a96533c06c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/s-zeng/dhall-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - make install
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - poetry
    - cargo-bundle-licenses
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - dhall
  commands:
    - make test

about:
  home: https://github.com/s-zeng/dhall-python
  summary: 'Python bindings for Dhall, a functional configuration language'
  description: |
    Dhall-python contains the Python bindings for Dhall, implemented in Rust.
  license: MIT
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - ndwarshuis
