{% set name = "pavo" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pavo-{{ version }}.tar.gz
  sha256: 045856344a6fe88aca0ae965f410adf2784309d3bb61920303edefa0b2f74a52

build:
  entry_points:
    - pavo = pavo.__main__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=62.4
    - wheel
    - setuptools-scm >=6.2
    - pip
    - nodejs =16.*
  run:
    - python >=3.8
    - celery
    - click
    - dynaconf
    - filelock
    - flask-caching >=1.8.0
    - flask >=2
    - fsspec
    - geopandas
    - gunicorn
    - importlib-resources
    - itsdangerous
    - orjson
    - pado >=0.12
    - pandas
    - pillow
    - redis-py
    - tiffslide >=2
    - tqdm
    - typer
    - typing-extensions
    - werkzeug

test:
  imports:
    - pavo
  commands:
    - pip check
    - pavo --help
  requires:
    - pip

about:
  home: https://github.com/bayer-group/pavo
  summary: PAthological Visualisation Obsession
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ap--
