{% set name = "libgazebo-yarp-plugins" %}
{% set version = "4.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/robotology/gazebo-yarp-plugins/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 26e4f26ca5799f445bef9ad5ef307da4b180bebe593a1c925246598eb61b8521

build:
  number: 0
  skip: true  # [osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    - multisheller
  host:
    - yarp-cxx
    - gazebo
    - libsdformat
    - libignition-math6
    - libprotobuf
    - tbb
    - libopencv

test:
  commands:
    - test -f ${PREFIX}/include/GazeboYarpPlugins/common.hh  # [not win]
    - test -f ${PREFIX}/lib/libgazebo-yarp-camera${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\\GazeboYarpPlugins\\common.hh exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\gazebo-yarp-camera.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gazebo-yarp-camera.lib exit 1  # [win]

about:
  home: https://github.com/robotology/gazebo-yarp-plugins
  license: LGPL-3.0-only
  license_file: LGPL3.TXT 
  summary: 'Plugins to interface Gazebo with YARP. '

extra:
  feedstock-name: gazebo-yarp-plugins
  recipe-maintainers:
    - traversaro
