{% set name = "libgazebo-yarp-plugins" %}
{% set version = "4.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/robotology/gazebo-yarp-plugins/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 57666d4af26fb7b00802d8c3fc42de5bdcf471b4300a3f5fe71f75a94de14191

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja

  host:
    - yarp-cxx
    - gazebo
    - dartsim
    - libopencv

test:
  commands:
    - test -f ${PREFIX}/include/GazeboYarpPlugins/common.hh # [not win]
    - test -f ${PREFIX}/lib/libgazebo-yarp-camera${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\\GazeboYarpPlugins\\common.hh exit 1  # [win]
    - if not exist %%LIBRARY_BIN%\\gazebo-yarp-camera.dll exit 1  # [win]
    - if not exist %%LIBRARY_LIB%\\gazebo-yarp-camera.lib exit 1  # [win]

about:
  home: https://github.com/robotology/gazebo-yarp-plugins
  license: LGPL-3.0-only
  license_file: LGPL3.TXT 
  summary: 'Plugins to interface Gazebo with YARP. '

extra:
  feedstock-name: gazebo-yarp-plugins
  recipe-maintainers:
    - traversaro
