{% set name = "nectarchain" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nectarchain-{{ version }}.tar.gz
  sha256: e421ecf3ef51f70cd0e033cdd03d2d638afb4f3886a361cfd79e874b5a5732f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: True  # [win]

requirements:
  host:
    - python >=3.8
    - setuptools >=64.0.3
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.8
    - astropy >=4.2,<5.dev0
    - ctapipe >=0.12,<1.dev0
    - numpy >=1.22,<2.dev0
    - protozfits >=2.0,<3.dev0
    - pytables >=3.7

test:
  imports:
    - nectarchain
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cta-observatory/nectarchain
  summary: Analysis chain for the CTA MSTN NectarCAM prototype
  license: BSD-3-Clause
  license_file: licenses/LICENSE.rst

extra:
  recipe-maintainers:
    - jlenain
