{% set name = "duckargs" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eriknyquist/duckargs/archive/v{{ version }}.tar.gz
  sha256: 82e9fff439290a4927ffe2f996b66fd5eccec161b5fe1354548c16d358396e52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - duckargs
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/eriknyquist/duckargs
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
