{% set name = "paseos" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/paseos-{{ version }}.tar.gz
  sha256: c00416670f3f924dfa1dc42435a6612324ede1db4e845f0937238d9ccf611bfc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --ignore-requires-python
  number: 0

requirements:
  host:
    - python >=3.8,<4
    - pip
  run:
    - python >=3.8,<4
    - dotmap >=1.3.30
    - loguru >=0.6.0
    - matplotlib-base >=3.6.0
    - numpy ==1.23.5
    - pykep >=2.6
    - scikit-spatial >=6.5.0
    - skyfield >=1.45
    - toml >=0.10.2
    - tqdm >=4.64.1

test:
  imports:
    - paseos
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aidotse/paseos
  summary: A package which simulates the space environment for operating multiple spacecraft.
  dev_url: https://github.com/aidotse/paseos/
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gomezzz
