{% set name = "articdb" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/man-group/ArcticDB
  git_rev: experimental/conda-forge-release
  git_depth: 1

build:
  skip: true  # [win]
  script:  ARCTICDB_USING_CONDA=1 {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make

  host:
    - python
    - pip
    - folly ==2022.10.31
    - lz4-c
    - prometheus-cpp
    - double-conversion
    - libevent
    - libprotobuf <4
    - libmongocxx
    - zstd
    - pybind11
    - pcre
    - gflags
    - cyrus-sasl
    - msgpack-c
    - aws-sdk-cpp
    - bitmagic
    - krb5
    - xxhash
    - semimap

  run:
    - python
    - numpy
    - pandas
    - boto3

test:
  imports:
    - ArcticDB

about:
  home: https://github.com/man-group/ArcticDB
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
  description: |
    simplejson is a simple, fast, complete, correct and extensible
    JSON <https://json.org> encoder and decoder for Python 2.5+ and
    Python 3.3+. It is pure Python code with no dependencies, but includes
    an optional C extension for a serious speed boost.
  license: BUSL-1.1
  license_family: OTHER
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - DerThorsten
