{% set name = "articdb" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/man-group/ArcticDB
  git_rev: experimental/conda-forge-release
  git_depth: 1

build:
  # We skip the build on Windows because one of the dependencies (folly)
  # is not available for Windows.
  # See:
  skip: true  # [win]
  script: ARCTICDB_USING_CONDA=1 {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make

  host:
    - python
    - pip
    - folly
    - lz4-c
    - prometheus-cpp
    - double-conversion
    - libevent
    - libprotobuf <4
    - libmongocxx
    - zstd
    - pybind11
    - pcre
    - gflags
    - cyrus-sasl =2.1.27
    - msgpack-c
    - aws-sdk-cpp
    - bitmagic
    - krb5 =1.20.1
    - xxhash
    - semimap

  run:
    - python
    - numpy
    - pandas
    - enum-compat
    - grpcio-tools
    - protobuf
    - python-attr
    - six
    - psutil
    - pyyaml
    - decorator
    - prometheus_client

test:
  imports:
    - arcticdb

about:
  home: https://arcticdb.io/
  summary: "ArcticDB is a high performance, serverless DataFrame database built for the Python Data Science ecosystem."
  description: |
    "**ArcticDB** is a high performance, serverless **DataFrame database** built for
    the Python Data Science ecosystem. Launched in March 2023, it is the successor
    to [Arctic](https://github.com/man-group/arctic).
    ArcticDB offers an intuitive Python-centric API enabling you to read and write
    Pandas DataFrames to S3 or LMDB utilising a fast C++ data-processing and
    compression engine."
  license: BUSL-1.1
  license_family: OTHER
  license_file: LICENSE.txt
  doc_url: https://docs.arcticdb.io
  dev_url: https://github.com/man-group/ArcticDB

extra:
  recipe-maintainers:
    - DerThorsten
    - jjerphan
