{% set name = "oasis-deconv" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oasis-deconv-{{ version }}.tar.gz
  sha256: bf5e061498927a52dd58e9a1c6416ff175a42591b8ef16cd2d0f76dbf832b825

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - wheel
    - numpy
    - cython
    - pip
  run:
    - python
    - scipy
    - matplotlib-base
    - cython
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - oasis
  requires:
    - pip
    # - pytest
    - setuptools<=64.0.2
    - cvxpy
  # source_files:
  #   - tests
  commands:
    - pip check
    - {{ PYTHON }} run_test.py 

about:
  home: https://github.com/j-friedrich/OASIS
  summary: Fast algorithm for deconvolution of neural calcium imaging traces
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JohannesFriedrich
