{% set version = "1.0.4" %}

package:
  name: leb128
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/l/leb128/leb128-{{ version }}.tar.gz
    sha256: 3552deeae400b835f86e0d32eb7c737a75eb167c0eb551b70268d522633581af
  # TODO: remove after https://github.com/mohanson/leb128/pull/6
  - fn: LICENSE-leb128-{{ version }}
    url: https://raw.githubusercontent.com/mohanson/leb128/v{{ version }}/LICENSE
    sha256: 6d21d47a22d95b919ddeaf8b49a4697909b47310472cb7fe3ad14cf6810d3208

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - leb128
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mohanson/leb128
  summary: LEB128(Little Endian Base 128)
  license: MIT
  license_file: LICENSE-leb128-{{ version }}

extra:
  recipe-maintainers:
    - bollwyvl
