# conda-forge feedstock (i.e. `conda install -c conda-forge <project_name>`)
{% set project_name = "evalhyd-cli" %}
# gitlab repository
{% set repository_name = "evalhyd-cli" %}
{% set version = "0.1.0.0" %}
{% set sha256 = "38ebcc4915542b0887d4178724643539355b043a7aa4a68bdeacce4629bd1f11" %}
# command line (i.e. `$ <command_name> --help`)
{% set command_name = "evalhyd" %}

package:
  name: {{ project_name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/{{ repository_name }}/-/archive/v{{ version }}/{{ repository_name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make                    # [unix]
  host:
    - xtl >=0.7.5
    - xtensor >=0.24.6
    - cli11 >=2.3.1
    - libevalhyd ==0.1.0

test:
  commands:
    - |
      {{ command_name }} --help
    - |
      {{ command_name }} evald --help
    - |
      {{ command_name }} evalp --help

about:
  home: https://hydrogr.github.io/evalhyd
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENCE.rst
  summary: A command line interface for evalhyd, a C++ library to evaluate streamflow predictions
  description: |
    An command line executable to evaluate deterministic and 
    probabilistic streamflow predictions
  doc_url: https://hydrogr.github.io/evalhyd/cli
  dev_url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/{{ repository_name }}

extra:
  recipe-maintainers:
    - ThibHlln
