# name for conda package (i.e. `conda install -c conda-forge <project_name>`)
{% set project_name = "evalhyd-cli" %}
# name for command
{% set command_name = "evalhyd" %}
{% set version = "0.1.0.0" %}
{% set sha256 = "dd5e80d53ebdbd5a1f6d8aef285fd4362fa7c5b622176b2e800d07f510e302d0" %}

package:
  name: {{ project_name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/{{ project_name }}/-/archive/v{{ version }}/{{ project_name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true                  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >= 3.15
    - make                    # [unix]
    - ninja                   # [win]
  host:
    - xtl >=0.7.5
    - xtensor >=0.24.6
    - cli11 >= 2.3.1
    - evalhyd-cpp == 0.1.0

test:
  commands:
    - {{ command_name }} '--help'
    - {{ command_name }} 'evald' '--help'
    - {{ command_name }} 'evalp' '--help'

about:
  home: https://hydrogr.github.io/evalhyd
  license: GPL-3
  license_family: GPL
  license_file: LICENCE
  summary: A command line interface for evalhyd, a C++ library to evaluate streamflow predictions
  description: |
    An command line executable to evaluate deterministic and 
    probabilistic streamflow predictions
  doc_url: https://hydrogr.github.io/evalhyd/cli
  dev_url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/{{ project_name }}

extra:
  recipe-maintainers:
    - ThibHlln
