{% set name = "parsita" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/parsita-{{ version }}.tar.gz
  sha256: 0ecfed08b6c95b5403dd7e0f8ef98cfc903b8348a379d16b0841bfa466081cee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7,<4.0

test:
  imports:
    - parsita
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/drhagen/parsita
  summary: Parser combinator library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - drhagen
