{% set name = "f77_zmq" %}
{% set version = "4.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zeromq/f77_zmq/releases/download/v{{ version }}/f77-zmq-{{ version }}.tar.gz
  sha256: 431a7539283caf5cc3daa6df99b314c49bc7598129e28cd377f86ea8b3695ef9

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    - make check
  host:
    - zeromq
  run:
    - zeromq

test:
  commands:
    - test -f ${PREFIX}/lib/libf77zmq.so     # [linux]
    - test -f ${PREFIX}/lib/libf77zmq.dylib  # [osx]

about:
  home: https://github.com/zeromq/f77_zmq
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: f77_zmq/LICENSE
  summary: 'Fortran77 interface for the ZeroMQ library'

extra:
  recipe-maintainers:
    - scemama
