{% set name = "f77_zmq" %}
{% set version = "4.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zeromq/f77_zmq/releases/download/v4.3.2_autotools/f77-zmq-4.3.2.tar.gz
  sha256: e027bf1017ca6b47ce4a3481ae5b255db8ea86294bc32f1207bd90dbdece7671

build:
  number: 0
  script: "./configure && make && make install"
  skip: true    # [win]
  skip: true    # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
  host:
    - zeromq
  run:
    - zeromq

test:
￼  commands:
￼    - test -f ${PREFIX}/lib/libf77zmq.a           # [unix]
￼    - test -f ${PREFIX}/lib/libf77zmq.so          # [linux]

about:
  home: https://github.com/zeromq/f77_zmq
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: 'Fortran77 interface for the ZeroMQ library'

extra:
  recipe-maintainers:
    - scemama
