{% set name = "TraffiX" %}
{% set version = "0.1.2a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/TraffiX-{{ version }}.tar.gz
  sha256: 30b23b21d584fde051699082ea16447948363eda8d4f6280bdf791d920090e81

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - osmnx >=1.3.0,<1.4.dev0
    - pandas >=1.2.4,<1.3.dev0

test:
  imports:
    - TraffiX
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Ultios/StraPy
  summary: A package for macroscopic transportation assignment.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Ultios
