{% set name = "traffix" %}
{% set version = "0.1.7a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/traffix-{{ version }}.tar.gz
  sha256: c504dc6ad4d4a2309a37ae0254edf2f100e21df4d24d723a6254a395d5055e46

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - osmnx >=1.3.0,<1.4.dev0
    - pandas >=1.2.4,<1.3.dev0

test:
  imports:
    - traffix
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Ultios/traffix
  summary: A package for macroscopic transportation assignment.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Ultios
