{% set name = "traffix" %}
{% set version = "0.1.11a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/traffix-{{ version }}.tar.gz
  sha256: 19e53b8d0f6a4f7072c673e4da16f215499eb3d8f73bb124b9fdb6efcd31539e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - osmnx >=1.3.0
    - pandas >=1.5
    - geopandas >=0.12
    - matplotlib-base >=3.5
    - networkx >=2.8
    - numpy >=1.23
    - pyproj >=3.4
    - requests >=2.28
    - shapely >=2.0

test:
  imports:
    - traffix
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Ultios/traffix
  summary: A package for macroscopic transportation assignment.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Ultios
