{% set name = "mplcyberpunk" %}
{% set version = "0.7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: c7e17dd62cea31b7147b273bad7679fb396cf42fb210c59ba0b4a00d1334f84c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib
    - pip
    - python
  run:
    - matplotlib
    - python

test:
  imports:
    - mplcyberpunk

about:
  home: "https://github.com/dhaitz/mplcyberpunk"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Add-on for Matplotlib to produce 'Cyberpunk' style plots"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
