{% set name = "adam-robotics" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ami-iit/ADAM/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4a726ac0c0ce6735eb51be30f512583d63721a270d16cb74738f78615540a6cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - wheel
    - setuptools
  run:
    - python >=3.7
    - numpy
    - scipy
    - casadi
    - prettytable
    - urdfdom-py

test:
  source_files:
    - tests
  imports:
    - adam
  commands:
    - pytest ./tests/ -v
  requires:
    - pip
    - pytest
    - gym-ignition-models
    - pytorch
    - jax
    - idyntree

about:
  home: https://github.com/ami-iit/ADAM
  summary: 'ADAM implements a collection of algorithms for calculating rigid-body dynamics in Jax, CasADi, PyTorch, and NumPy.'
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - Giulero
