{% set name = "lmdbxx" %}
{% set version = "0.9.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/drycpp/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: 8121cc0a3f856584c5ce79638614468e2aba617d0338d14871f4ec7acbee2bec

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    
test:
  commands:
    - test -e include/lmdbxx/no_locking_policy.hpp
    - test -e include/lmdbxx/shared_pool.hpp
    - test -e include/lmdbxx/unique_pool.hpp

about:
  home: https://github.com/drycpp/lmdbxx
  summary: This is a comprehensive C++ wrapper for the LMDB embedded database library,
  description: This is a comprehensive C++ wrapper for the LMDB embedded database library, offering both an error-checked procedural interface and an object-oriented resource interface with RAII semantics.


  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers: 
    - DerThorsten
