{% set name = "flux-sched" %}
{% set version = "0.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flux-framework/flux-sched/releases/download/v{{ version }}/flux-sched-{{ version }}.tar.gz
  sha256: 2b3a0c466fb4a1014ea131c2b8ea7c519f9278eba73d6fcb361b7bdb4fd494e9

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - pkgconfig
    - jq
  host:
    - python
    - flux-core
    - libhwloc
    - boost
    - libedit
    - yaml-cpp 
  run:
    - python
    - flux-core
    - boost

test:
  commands:
    - flux --help

about:
  home: https://flux-framework.org
  summary: 'Fluxion Graph-based Scheduler'
  description: |
    Welcome to Fluxion, an advanced job scheduling software tool for 
    High Performance Computing (HPC). Fluxion combines graph-based 
    resource modeling with efficient temporal plan management schemes to 
    schedule a wide range of HPC resources (e.g., compute, storage, power 
    etc) in a highly scalable, customizable and effective fashion.
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://flux-framework.readthedocs.io/
  dev_url: https://github.com/flux-framework/flux-sched

extra:
  recipe-maintainers:
    - jan-janssen
