{% set name = "libvulkan-loader" %}
{% set version = "1.3.239.0" %}

package:
  name: {{ name }}
  version: {{ version }}

# For this repo, v**** tags exists, but apparently the stable tags (the one corresponding to versions
# that are available for download at https://vulkan.lunarg.com/sdk/home) are the sdk-*** ones
# See https://github.com/KhronosGroup/Vulkan-Headers#version-tagging-scheme
source:
  url: https://github.com/KhronosGroup/Vulkan-Loader/archive/refs/tags/sdk-{{ version }}.tar.gz
  sha256: 6e16051ccb28821b907a08025eedb82cc73e1056924b32f75880ecae2499f7f6

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - python
  host:
    - libvulkan-headers {{ version }}
  run_constrained:
    - libvulkan-headers {{ version }}

test:
  commands:
    - test -f ${PREFIX}/lib/libvulkan${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_LIB%\\vulkan.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\vulkan.dll exit 1  # [win]

about:
  home: https://github.com/KhronosGroup/Vulkan-Loader
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Khronos official Vulkan ICD desktop loader for Windows, Linux, and MacOS.

extra:
  feedstock-name: vulkan-loader
  recipe-maintainers:
    - traversaro
