{% set name = "libcufile" %}
{% set version = "1.5.0.59" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set extension = "tar.xz" %}  # [not win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/{{ name }}/{{ platform }}/{{ name }}-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 222c49b29afb544c69542c4e658b0a1bd01fd2306f2136ad6990ccfff482a097  # [linux64]
  sha256: 4e8d2b525322be9ab6ae574bd1d0325a4bf9c6c3bbdaa1611b5b969b7b34b0c4  # [aarch64]
  patches:
    - Makefile.patch

build:
  number: 0
  skip: true  # [osx]
  skip: true  # [ppc64le]
  skip: true  # [aarch64]
  skip: true  # [win]

outputs:
  - name: libcufile
    files:
      - lib/libcufile*.so.*
      - etc/cufile.json
      - man
    test:
      commands:
        - test -f $PREFIX/lib/libcufile*.so.*
        - test -f $PREFIX/etc/cufile.json

  - name: libcufile-dev
    requirements:
      run:
        - libcufile >={{ version }}
    files:
      - lib/libcufile*.so
      - targets/*/lib/libcufile*.so
      - include/cufile*
      - targets/*/include/cufile*
    test:
      commands:
        - test -f $PREFIX/lib/libcufile*.so
        - test -f $PREFIX/include/cufile*

  - name: libcufile-static
    requirements:
      run:
        - libcufile-dev >={{ version }}
    files:
      - lib/libcufile*_static.a
      - targets/*/lib/libcufile*_static.a
    test:
      commands:
        - test -f $PREFIX/lib/libcufile*_static.a

  - name: gds-tools
    requirements:
      run:
        - libcufile >={{ version }}
    files:
      - gds/samples
      - gds/tools
    test:
      commands:
        - test -d $PREFIX/gds/samples
        - test -d $PREFIX/gds/tools

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: |
    Library for GPU Direct Storage with CUDA
  doc_url: https://docs.nvidia.com/gpudirect-storage/api-reference-guide/index.html

extra:
  recipe-maintainers:
    - adibbley
