{% set name = "enpt_enmapboxapp" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/enpt_enmapboxapp-{{ version }}.tar.gz
  sha256: f3bfa3a30a536cf5fa1e0c4b285f64ff5b919940965471a46547d97c6104bdcd

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - importlib-metadata
    - packaging
    - pip
  run:
    - python
    - importlib-metadata
    - packaging
    - psutil
    - qgis>=3.28.2

test:
  imports:
    - enpt_enmapboxapp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/enpt_enmapboxapp
  summary: A QGIS EnMAPBox plugin providing a GUI for the EnMAP processing tool (EnPT).
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
