{% set name = "skbase" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skbase-{{ version }}.tar.gz
  sha256: 0f1c113fe094725f22619b30c6c8093ec77027d937adf1c2246de9344f10228e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.12
    - pip
  run:
    - python >=3.7,<3.12
    - scikit-learn <1.3.0,>=0.24.0
    - typing-extensions
    - pytest

outputs:
  - name: {{ name|lower }}
    script: {{ PYTHON }} -m pip install . -vv

    requirements:
      build:
        - python
      host:
        - python >=3.7,<3.12
        - pip
      run:
        - python >=3.7,<3.12
        - scikit-learn <1.3.0,>=0.24.0
        - typing-extensions
        - pytest
      
    test:
      imports:
        - skbase
        - skbase.base
        - skbase.lookup
        - skbase.testing
        - skbase.validate
      commands:
        - pip check
      requires:
        - pip

  - name: skbase-all-extras
    requirements:
      build:
        - python
      host:
        - python >=3.7,<3.12
        - pip
      run:
        - python >=3.7,<3.12
        - {{ pin_subpackage("skbase", exact=True) }}
        - scikit-learn <1.3.0,>=0.24.0
        - typing-extensions
        - pytest
        - pandas
    
    test:
      imports:
        - skbase
        - skbase.base
        - skbase.lookup
        - skbase.testing
        - skbase.validate
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/sktime/skbase
  summary: Base classes for sklearn-like parametric objects
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://skbase.readthedocs.io/en/latest/
  dev_url: https://github.com/sktime/skbase

extra:
  recipe-maintainers:
    - RNKuhns
