 {% set version = "4.0.1" %}
package:
  name: pyside6qtads
  version: {{ version }}

source:
  url: https://github.com/mborgerson/pyside6_qtads/archive/v{{ version }}.tar.gz
  sha256: bb6c7efb88df26463ddfd0c25083a002e301495ec382333dd07b2155a77b2f57
  patches:
    - 0001-CMakeLists.patch
    - 0002-generate_pyi.patch
    - 0003-setup.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - cmake
    - {{ compiler('c') }}            # [not osx]
    - {{ compiler('cxx') }}          # [not osx]
    - clangdev
    - ninja
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]

  host:
    - python
    - cmake-build-extension
    - qt6-main
    - {{ pin_compatible('qt6-ads', max_pin='x.x') }}
    - pyside6
    - pip
    - setuptools
    - xorg-libxfixes                 # [linux]
    
  run:
    - python
    - pyside6
    - {{ pin_compatible('qt6-ads', max_pin='x.x') }}
    
test:
  imports:
    - PySide6QtAds

about:
  home: https://github.com/mborgerson/pyside6_qtads
  license: LGPL-2.1-only
  license_file: LICENSE
  summary: PySide6 bindings for Qt-Advanced-Docking-System

extra:
  recipe-maintainers:
    - n-elie
