{% set name = "patchworklib" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ponnhide/patchworklib/archive/v{{ version }}.tar.gz
  sha256: 973088de5943505fbf40a8a0b4cf8fe847f86ec4c8e4fd69865147850b466adc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base >=3.4
    - pandas >=0.24
    - numpy >=1.16
    - dill

test:
  imports:
    - patchworklib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ponnhide/patchworklib
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ponnhide
    - hoeze
