{% set name = "patchworklib" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ponnhide/patchworklib/archive/v{{ version }}.tar.gz
  sha256: 973088de5943505fbf40a8a0b4cf8fe847f86ec4c8e4fd69865147850b466adc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base >=3.4
    - pandas >=0.24
    - numpy >=1.16
    - dill

test:
  imports:
    - patchworklib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ponnhide/patchworklib
  license: GPL-3.0-only
  license_file: LICENSE
  summary: 'patchwork for matplotlib'
  description: |
    Patchworklib is a universal composer of matplotlib-related plots (simple matplotlib plots, Seaborn plots (both axis-level and figure-level), and plotnine plots). This library is inspired by patchwork for ggplot2. Accordingly, as original patchwork, users can easily align matplotlib plots with only "/" and "|" operators.

    Additionally, several third-party libraries based on matplotlib, such as plotnine and seaborn, provide functions to generate beautiful plots with simple python codes, but many of those plots cannot be handled as matplotlib subplots. Therefore, their placement must be adjusted manually. Now, scientists spend their valuable time arranging figures.

    Patchworklib provides a solution for the problem. By using patchworklib, any kind of seaborn and plotnine plots can be handled as matplotlib subplots.

extra:
  recipe-maintainers:
    - ponnhide
    - hoeze
