{% set name = "balance" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/balance/archive/{{ version }}.tar.gz
  sha256: 78d5335f73c9906571059c4c08b323e272242e4600e3f0f2f563798a748c2e9b

build:
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools-scm
    - python >=3.7
  run:
    - ipfn
    - ipython
    - matplotlib-base
    - numpy
    - patsy
    - pandas <=1.4.3
    - plotly
    - python >=3.7
    - seaborn <=0.11.1
    - scikit-learn
    - scipy <=1.8.1
    - statsmodels

test:
  source_files:
    - tests
  imports:
    - balance
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://import-balance.org/
  dev_url: https://github.com/facebookresearch/balance
  summary: Simple workflow and methods for dealing with biased data.
  license: GPL-2.0-only
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
