{% set name = "balance" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/balance/archive/{{ version }}.tar.gz
  sha256: b975b2a21a17089b97f87d3caa996a7224a39e80449b11f6a03d4ab6dec18e3a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas <=1.4.3
    - ipython
    - scipy <=1.8.1
    - patsy
    - seaborn <=0.11.1
    - plotly
    - matplotlib-base
    - statsmodels
    - scikit-learn
    - ipfn

test:
  imports:
    - balance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facebookresearch/balance
  summary: the blessed package to manage your versions by scm tags
  license: GPL-2.0 & EPL-2.0
  license_file:
    - LICENSE
    - LICENSE-DOCUMENTATION

extra:
  recipe-maintainers:
    - MattChanTK
