{% set name = "wield.declarative" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wield.declarative-{{ version }}.tar.gz
  sha256: e6b3d1af02778d6d3a331b433c6dc55f0371d5e8085f3f62a91f36852afcec28

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=45
    - wheel
    - pip
  run:
    - python >=3.6
    - setuptools-scm >=6.0.0

test:
  imports:
    - wield.declarative
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wieldphysics/wield-declarative
  summary: Base classes and methods for declarative object instantiation
  license: Apache-2.0
  license_file: LICENSES/

extra:
  recipe-maintainers:
    - mccullerlp 
