{% set version = "3.0-rc1" %}

package:
  name: vtkbool
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/zippy84/vtkbool/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a422662a7679b6f7e433596c4f80e1569e2b1c55b6a277c008881cd3ca4f7e1a

requirements:
  build:
    - python {{ python }}
    - cmake
    - {{ compiler('cxx') }}
    - ninja
  host:
    - python {{ python }}
    - vtk
  run:
    - python {{ python }}
    - vtk

test:
  imports:
    - vtkbool
