{% set version = "3.0rc1" %}
{% set vtkbool_version = "3.0-rc1" %}

package:
  name: vtkbool
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/zippy84/vtkbool/archive/refs/tags/v{{ vtkbool_version }}.tar.gz
  sha256: a422662a7679b6f7e433596c4f80e1569e2b1c55b6a277c008881cd3ca4f7e1a
  patches:
    - modify-cmakelists.patch  # patch cmakelists to support building in conda env

requirements:
  build:
    - python {{ python }}
    - cmake
    - {{ compiler('cxx') }}
    - ninja
  host:
    - python {{ python }}
    - vtk
  run:
    - python {{ python }}
    - vtk

test:
  imports:
    - vtkbool

about:
  home: https://github.com/zippy84/vtkbool
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A VTK-based library for boolean operations on polygonal meshes.
  description: |
    vtkbool is a library for boolean operations on polygonal meshes,
    based on VTK. vtkbool is developed by by Ronald Römer (@zippy84).
  doc_url: https://github.com/zippy84/vtkbool/README.md
  dev_url: https://github.com/zippy84/vtkbool

extra:
  recipe-maintainers:
    - whophil
