{% set version = "3.0-rc1" %}

package:
  name: vtkbool
  version: {{ version }}

build:
  number: 0

source:
  - url: https://github.com/zippy84/vtkbool/archive/refs/tags/v{{ version }}.tar.gz

requirements:
  build:
    - python {{ python }}
    - cmake
    - {{ compiler('cxx') }}
    - ninja
  host:
    - python {{ python }}
    - vtk
  run:
    - python {{ python }}
    - vtk

test:
  imports:
    - vtkbool
