{% set name = "pyseobnr" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyseobnr-{{ version }}.tar.gz
  sha256: 87aa14dcc3b3352b0e38cf05143128aa0c0ad3de1af20807eb06a30b9e5bdcf3

build:
  skip: true  # [py<38 or win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - setuptools-scm >=3.4.3
    - wheel
    - cython
    - numpy
    - scipy
    - pip
    - gsl >=2.7
    - swig >=4.0
  run:
    - python
    - scipy >=1.8.0
    - matplotlib-base
    - h5py
    - numexpr
    - numba
    - qnm
    - scri
    - setuptools
    - jax
    - jaxlib
    - gsl >=2.7
    - rich
    - pygsl
    - lalsuite
    - numpy >=1.23

test:
  imports:
    - pyseobnr
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Gravitational wave modelling within the effective-one-body framework
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SergeiOssokine
