{% set name = "CSET" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/CSET-{{ version }}.tar.gz
  sha256: 390fd03a089be03a554493654fcdeb542319bb759fc357270e36ce618136638b

build:
  skip: true  # [py<38]
  entry_points:
    - cset = CSET:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - numpy
    - scitools-iris
    - mo_pack
    - tomli >=1.1.0  # [py<311]
    - importlib-resources >=3.0.0  # [py<39]

test:
  imports:
    - CSET
  commands:
    - pip check
    - cset --help
    - pytest
  source_files:
    - tests
  requires:
    - pip
    - pytest

about:
  summary: Convective Scale Evaluation Tool for evaluation and investigation of regional models.
  dev_url: https://github.com/MetOffice/CSET
  license: Apache-2.0
  license_file: LICENCE

extra:
  recipe-maintainers:
    - jfrost-mo
