# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe
# If your package is python based, we recommend using Grayskull to generate it instead:
# https://github.com/conda-incubator/grayskull

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "perl-uri" %}
{% set version = "5.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # https://cpan.metacpan.org/authors/id/O/OA/OALDERS/URI-5.17.tar.gz
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/URI-5.17.tar.gz
  # If getting the source from GitHub, remove the line above,
  # uncomment the line below, and modify as needed. Use releases if available:
  # url: https://github.com/simplejson/simplejson/releases/download/{{ version }}/simplejson-{{ version }}.tar.gz
  # and otherwise fall back to archive:
  # url: https://github.com/simplejson/simplejson/archive/v{{ version }}.tar.gz
  sha256: 5f7e42b769cb27499113cfae4b786c37d49e7c7d32dbb469602cd808308568f8
  # sha256 is the preferred checksum -- you can get it for a file with:
  #  `openssl sha256 <file name>`.
  # You may need the openssl package, available on conda-forge:
  #  `conda install openssl -c conda-forge``

build:
  noarch: generic
  number: 0

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - make
  host:
    - perl 5.32.1
    - perl-business-isbn
    - perl-carp
    - perl-constant
    - perl-data-dumper
    - perl-encode
    - perl-exporter
    - perl-extutils-makemaker
    - perl-file-path
    - perl-file-temp
    - perl-mime-base64
    - perl-parent
    - perl-test
    - perl-test-harness
    - perl-test-needs
    - perl-test-warnings
    - perl-test-fatal
  run:
    - perl >=5.32.1,<5.33.0a0 *_perl5
    - perl-business-isbn
    - perl-carp
    - perl-constant
    - perl-data-dumper
    - perl-encode
    - perl-exporter
    - perl-mime-base64
    - perl-parent

test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - URI

about:
  home: https://github.com/libwww-perl/URI
  summary: 'Uniform Resource Identifiers (absolute and relative)'
  description: |
    This module implements the URI class. Objects of this class represent "Uniform Resource Identifier references" as specified in RFC 2396 (and updated by RFC 2732).
  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  # See https://spdx.org/licenses/
  license: GPL-1.0-or-later
  # It is required to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file: LICENSE
  # The doc_url and dev_url are optional.
  dev_url: https://github.com/libwww-perl/URI

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - fgiacomoni
