{% set name = "popfinder" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/popfinder-{{ version }}.tar.gz
  sha256: cda5e7a09c31cdf068e578eb8ca6f7df7ff46cf5531ecb9ac67c835a55fd4fd6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - popfinder
    - tests
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  home: https://syncrosim.com/
  summary: Genetic population assignment using neural networks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - katieb1
