{% set name = "clapper" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/clapper-{{ version }}.tar.gz
  sha256: b6e8e78731fec3564a21a094354ffa93600a0b22a3acaf9d974676841f22121d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >=3.9
    - click >=8
    - tomli
    - tomli-w
    - xdg

test:
  source_files:
    - tests
  imports:
    - clapper
  commands:
    - pip check
    - PYTHONPATH=. pytest -sv tests
  requires:
    - pip
    - pytest

about:
  home: https://gitlab.idiap.ch/software/clapper
  doc_url: https://clapper.readthedocs.io
  dev_url: https://gitlab.idiap.ch/software/clapper
  summary: Configuration Support for Python Packages and CLIs
  license: BSD-3-Clause
  license_file: LICENSES/BSD-3-Clause.txt

extra:
  recipe-maintainers:
    - anjos
