{% set name = "cuda-cudart" %}
{% set version = "12.0.107" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_cudart/{{ platform }}/cuda_cudart-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: c0e16e9593a69afe4997ae96a8b024e751ebce0254523fd969b08bb028582d23  # [linux64]
  sha256: d785fd613e35e3761fdb0016a31a56417f570605cbfb9a93ca9dc68be6789188  # [ppc64le]
  sha256: 5de248c6c203f6c91ce34256bbfc028bc87c1b0c552f9f51edb65e60ad665f63  # [aarch64]
  sha256: 1cd8516feee068c6d718453e76b0dfcbee27844a35d4f3aa608a3d316190309c  # [win]

build:
  number: 0
  skip: true  # [osx]
  run_exports:                # [linux]
    strong:                   # [linux]
      - __glibc >=2.17        # [linux]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - sysroot_{{ target_platform }} 2.17   # [linux]
    - __glibc >=2.17                       # [linux]
  run:
    - sysroot_{{ target_platform }} 2.17   # [linux]
    - __glibc >=2.17                       # [linux]

test:
  commands:
    - test -f $PREFIX/lib/libcudart.so.{{ version }}  # [linux]

outputs:
  - name: cuda-cudart
    files:
      - lib/*.so.*            # [linux]
      - targets/*/lib/*.so.*  # [linux]
      - lib/x64/cuda.lib      # [win]
      - lib/x64/cudart.lib    # [win]

  - name: cuda-cudart-dev
    requirements:
      run:
        - cuda-cudart >={{ version }}
    files:
      - lib/*.so               # [linux]
      - targets/*/lib/*.so     # [linux]
      - include
      - targets/*/include/*.h  # [linux]
      - lib/x64/cudadevrt.lib  # [win]
      - bin                    # [win]

  - name: cuda-cudart-static
    requirements:
      run:
        - cuda-cudart-dev >={{ version }}
    files:
      - lib/*.a                    # [linux]
      - targets/*/lib/*.a          # [linux]
      - lib/x64/cudart_static.lib  # [win]

  - name: cuda-driver-dev
    build:
      skip: True                        # [not linux]
    files:
      - lib/stubs/libcuda.so
      - targets/*/lib/stubs/libcuda.so

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: CUDA Runtime native Libraries
  description: |
    CUDA Runtime native Libraries
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - adibbley
