{% set name = "litedram" %}
{% set version = "2022.12" %}
{% set sha256 = "087d128479d0126da1aac652018413ee1b712fb6294eafd75a596431bed54a64" %}

package:
   name: {{ name|lower }}
   version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-add-manifest-uplift-setup.py-to-pass-twine-checks.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  entry_points:
    - litedram_gen = litedram.gen:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - litex
    - pyyaml

test:
  imports:
    - litedram
  commands:
    - litedram_gen --help

about:
  home: https://github.com/enjoy-digital/litedram
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable DRAM core
  description: Small footprint and configurable DRAM core
  dev_url: https://github.com/enjoy-digital/litedram

extra:
  recipe-maintainers:
    - timkpaine
