{% set name = "TSDB" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WenjieDu/TSDB/archive/v{{ version }}.tar.gz
  sha256: 749cf413cb495a72d5a2f9d8db432b8d0044af428d878b0507f632c69d72cd12

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scikit-learn
    - pandas
    - scipy

test:
  imports:
    - tsdb
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/WenjieDu/TSDB
  summary: 'a python toolbox helping load time-series datasets easily'
  description: |
    Project TSDB is created to help researchers and engineers get rid of data collecting and downloading, 
    and focus back on data processing details. TSDB provides all-in-one-stop convenience for downloading 
    and loading open-source time-series datasets.
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://tsdb.readthedocs.io
  dev_url: https://github.com/WenjieDu/TSDB

extra:
  recipe-maintainers:
    - WenjieDu
