# name for conda package (i.e. `conda install -c conda-forge <project_name>`)
{% set project_name = "evalhyd-python" %}
# name for python package (i.e. `python -c "import <package_name>"`)
{% set package_name = "evalhyd" %}
{% set version = "0.1.0.0" %}
{% set sha256 = "c98a9583a40afea279a90d7c0249f25b8e04ebcc84f8ed1cd9712ade15fde2db" %}

package:
  name: {{ project_name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/{{ project_name }}/-/archive/v{{ version }}/{{ project_name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true                  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make                    # [unix]
    - python
    - pybind11
  host:
    - python
    - numpy
    - pybind11
    - xtl >=0.7.5
    - xtensor >=0.24.6
    - xtensor-python >=0.26.1
    - evalhyd-cpp == 0.1.0
  run:
    - python
    - numpy

test:
  imports:
    - {{ package_name }}
  commands:
    - pip check
    - python -c "import {{ package_name }}; assert {{ package_name }}.__version__ == '{{ version }}'"
  requires:
    - pip

about:
  home: https://hydrogr.github.io/evalhyd
  license: GPL-3
  license_family: GPL
  license_file: LICENCE
  summary: Python bindings for evalhyd, a C++ library to evaluate streamflow predictions
  description: |
    A Python package to evaluate deterministic and probabilistic 
    streamflow predictions
  doc_url: https://hydrogr.github.io/evalhyd/python
  dev_url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/{{ project_name }}

extra:
  recipe-maintainers:
    - ThibHlln
