{% set name = "urchin" %}
{% set version = "0.0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/urchin-{{ version }}.tar.gz
  sha256: 926525d34866f58d13109ee57df90842c03c15e7403b7b1bdb0febcf841219fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - lxml
    - networkx
    - numpy
    - pillow
    - pycollada >=0.6
    - pyribbit >=0.1.46
    - python >=3.6
    - scipy
    - six
    - trimesh
    - pip
  run:
    - python
    - lxml
    - networkx
    - numpy
    - pillow
    - pycollada >=0.6
    - pyribbit >=0.1.46
    - python >=3.6
    - scipy
    - six
    - trimesh

test:
  imports:
    - urchin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fishbotics/urchin
  summary: URDF parser and manipulator for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
