{% set name = "ssh-python" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ssh-python-{{ version }}.tar.gz
  sha256: f38778d40820d068e7b80ebabfb52bd5ff9b480a3b4c350fb6ab59c11886a96a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - krb5
    - libssh
    - openssl >=1.1
    - zlib
  host:
    - cython
    - pip
    - python
  run:
    - python

test:
  imports:
    - ssh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ParallelSSH/ssh-python
  doc_url: https://ssh-python.readthedocs.io/en/latest/index.html
  license: LGPL-2.1-or-later
  summary: libssh C library bindings for Python.
  license_file: COPYING

extra:
  recipe-maintainers:
    - thewchan
