{% set name = "TIES20" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UCL-CCS/TIES/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b3c6f7b1cb60415dc63f86ccc8a231c74bc1bc133746a3cde4b494f6fa686261

build:
  number: 0
  skip: True  # [win or osx and py==310]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ties = ties:cli.command_line_script

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - setuptools
  run:
    - python
    - ambertools >=20.0,<=22.0
    - ties_md =1.4.1
    - numpy
    - matplotlib-base
    - networkx
    - dwave-networkx
    - dimod
    - tabulate

test:
  imports:
    - ties
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - ties --help
    - python -m ties.testing.run

about:
  home: https://github.com/UCL-CCS/TIES20
  summary: 'Topology Superimposition based on joint graph traversal.'
  description: |
    Topology Superimposition based on joint graph traversal.
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://www.ties-service.org/
  dev_url: https://github.com/UCL-CCS/TIES20

extra:
  recipe-maintainers:
    - bieniekmateusz
    - adw62
