{% set name = "TIES20" %}
{% set version = "20.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UCL-CCS/TIES20/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5be7844fcecef02369b39320a4f5269d9297c0177302e23d42cf422e7ab90dc1

build:
  number: 0
  skip: True  # [win or osx and py==310]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ties = ties:cli.command_line_script

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - setuptools
  run:
    - python
    - ambertools >=20.0,<=22.0
    - ties_md =1.3
    - numpy
    - matplotlib-base
    - networkx
    - dwave-networkx
    - dimod
    - tabulate

test:
  imports:
    - ties
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - ls $PREFIX
    - pytest $SRC_DIR/../../../testing

about:
  home: https://github.com/UCL-CCS/TIES20
  summary: 'Topology Superimposition based on joint graph traversal.'
  description: |
    Topology Superimposition based on joint graph traversal.
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://www.ties-service.org/
  dev_url: https://github.com/UCL-CCS/TIES20

extra:
  recipe-maintainers:
    - bieniekmateusz
    - adw62
