{% set name = "TIES20" %}
{% set version = "20.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UCL-CCS/TIES20/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9ca19afea9f29434c2a4a6589e916c75d9e1c9242ae4a7f9464d55405aca7da0

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - ties = ties:cli.command_line_script

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python >=3.7
    - pip
    - numpy
    - cython
  run:
    - python >=3.7
    - ambertools >=20.0,<=22.0
    - libgfortran
    - ties_md
    - numpy
    - cython
    - setuptools
    - matplotlib-base
    - networkx
    - dimod
    - tabulate

test:
  imports:
    - ties
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "import pytest; pytest.main(['./TIES20-{{ version }}/testing'])"

about:
  home: https://github.com/UCL-CCS/TIES20
  summary: 'Topology Superimposition based on joint graph traversal.'
  description: |
    Topology Superimposition based on joint graph traversal.
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://www.ties-service.org/
  dev_url: https://github.com/UCL-CCS/TIES20

extra:
  recipe-maintainers:
    - bieniekmateusz
    - adw62
