{% set name = "TIES20" %}
{% set version = "20.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UCL-CCS/TIES20/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4af8f09bc480467ef8941dbc4f1a96edadb1dad6111929fc1b664eb67d266ef7

build:
  number: 0
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ties = ties:cli.command_line_script

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python >=3.7,<=3.9
    - pip
    - numpy
    - cython
    - setuptools
  run:
    - python >=3.7,<=3.9
    - ambertools >=20.0,<=22.0
    - ties_md =1.3
    - numpy
    - matplotlib-base
    - networkx
    - dwave-networkx
    - dimod
    - tabulate

test:
  imports:
    - ties
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "import pytest; pytest.main(['$SRC_DIR/../testing'])"

about:
  home: https://github.com/UCL-CCS/TIES20
  summary: 'Topology Superimposition based on joint graph traversal.'
  description: |
    Topology Superimposition based on joint graph traversal.
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://www.ties-service.org/
  dev_url: https://github.com/UCL-CCS/TIES20

extra:
  recipe-maintainers:
    - bieniekmateusz
    - adw62
