{% set version = '0.13.2.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-udunits2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/udunits2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/udunits2/udunits2_{{ version }}.tar.gz
  sha256: 9f5429c04a24930f7d037d506e5b154b6154df69247dcdaa6261075291d7f902

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('udunits2')"           # [not win]
    - "\"%R%\" -e \"library('udunits2')\""  # [win]

about:
  home: https://github.com/pacificclimate/Rudunits2 https://www.unidata.ucar.edu/software/udunits/
  license: GPL-2.0-or-later
  summary: Provides simple bindings to Unidata's udunits library.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - palderman
    - gonzarizzo

# Package: udunits2
# Type: Package
# Title: Udunits-2 Bindings for R
# Version: 0.13.2.1
# Date: 2022-03-11
# Authors@R: c(person("James", "Hiebert", email = "hiebert@uvic.ca", role = c("aut", "cre")), person("CRAN team",  role = c("ctb", "cph"), comment = "revisions/corrections in 2022"))
# Description: Provides simple bindings to Unidata's udunits library.
# URL: https://github.com/pacificclimate/Rudunits2 https://www.unidata.ucar.edu/software/udunits/
# SystemRequirements: udunits (>= 2) from https://www.unidata.ucar.edu/software/udunits/
# License: GPL-2
# LazyLoad: yes
# Depends: R (>= 2.10.0)
# NeedsCompilation: yes
# Packaged: 2022-03-11 17:05:45 UTC; ripley
# X-CRAN-Comment: Orphaned on 2022-01-06 as installation problems were not corrected.
# Maintainer: ORPHANED
# Repository: CRAN
# Date/Publication: 2022-03-11 20:00:50 UTC
# Author: James Hiebert [aut, cre], CRAN team [ctb, cph] (revisions/corrections in 2022)
# X-CRAN-Original-Maintainer: <ripley@stats.ox.ac.uk>
