{% set name = "cubed-xarray" %}
{% set version = "0.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 48a51b3c41a8d2b614f6baccc36077f5e2548b9d9463a6a3935c0633d36d3a3d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9

test:
  imports:
    - cubed_xarray
  commands:
    - pip check
  requires:
    - pip

about:
  home: The package home page
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE 
  summary: "Interface for using cubed with xarray for parallel computation."
  doc_url: https://github.com/xarray-contrib/cubed-xarray#readme
  dev_url: https://github.com/xarray-contrib/cubed-xarray

extra:
  recipe-maintainers:
    - TomNicholas
