{% set name = "quetz-sql-authenticator" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quetz-sql-authenticator-{{ version }}.tar.gz
  sha256: 80b74c14f512c6a35b0e22af7b4539df063c077aa66e57b6a721fcafc15e30a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - quetz.quetz-sql-authenticator = quetz_sql_authenticator.main
    - quetz.migrations.quetz-sql-authenticator = quetz_sql_authenticator.migrations
    - quetz.authenticator.sql-authenticator = quetz_sql_authenticator.main:SQLAuthenticator
    - quetz.models.quetz-sql-authenticator = quetz_sql_authenticator.db_models

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8
    - quetz >=0.4.4
    - sqlalchemy
    - fastapi
    - alembic
    - passlib

test:
  imports:
    - quetz_sql_authenticator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mamba-org/quetz-sql-authenticator
  summary: Manage simple credentials for your Quetz server
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - simonbohnen
    - wolfv
    - janjagusch
