{% set name = "napari-boxmanager" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_boxmanager-{{ version }}.tar.gz
  sha256: 2abecda5779245da21074e2053200579a9cf2926daa7c76753dc8d6a0b90cc26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - matplotlib-base
    - mrcfile
    - numpy ==1.23.5
    - pandas
    - pystardb

test:
  imports:
    - napari_boxmanager
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MPI-Dortmund/napari-boxmanager
  summary: Particle selection tool for cryo-em
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - mstabrin
