{% set name = "libmetgem" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/metgem/libmetgem/archive/v{{ version }}.tar.gz
  sha256: 83e3772a51da72cb2e93c224bcae2ba0494d1e7298ee44ed301c69eb95c72efe

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - cython
    - numpy
    - scipy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}
    - _openmp_mutex  # [linux]

test:
  imports:
    - libmetgem.cosine
    - libmetgem.database
    - libmetgem.filter
    - libmetgem.mgf
    - libmetgem.msp
    - libmetgem.neighbors
    - libmetgem.network

about:
  home: https://github.com/metgem/libmetgem
  summary: 'A library for molecular networking based on MS/MS spectra.'
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://libmetgem.readthedocs.io
  dev_url: https://github.com/metgem/libmetgem

extra:
  recipe-maintainers:
    - n-elie
