{% set name = "pennylane-lightning-gpu" %}
{% set version = "0.29.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  # - url: https://github.com/PennyLaneAI/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  #   sha256: e4cb8c496bddbb6c6cd27a6e1462cd3625952996222185dd0d7ec82e3cafea9b
  - git_url: https://github.com/PennyLaneAI/pennylane-lightning-gpu.git
    git_rev: d82ac5e116a0087b007ab81d48c117cdfa313728

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - cuquantum
    - ninja
    - make
  host:
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - pip
    - pybind11
    - python
    - wheel
  run:
    - pennylane
    - pip
    - python
test:
  imports:
    - pennylane_lightning_gpu
  requires:
    - pennylane
    - pip
    - python

about:
  home: https://docs.pennylane.ai/projects/lightning-gpu/en/latest/
  summary: The PennyLane-Lightning-GPU plugin extends the Pennylane-Lightning state-vector simulator written in C++, and offloads to the NVIDIA cuQuantum SDK for GPU accelerated circuit simulation.
  license: Apache-2.0
  # MIT is pennylane/grouping/graph_colouring.py
  license_file: LICENSE
  doc_url: https://docs.pennylane.ai/projects/lightning-gpu/en/latest/devices.html

extra:
  recipe-maintainers:
    - vincentmr
  feedstock-name: {{ name }}
