{% set name = "pennylane-lightning-gpu" %}
{% set version = "0.29.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  # - url: https://github.com/PennyLaneAI/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  #   sha256: e4cb8c496bddbb6c6cd27a6e1462cd3625952996222185dd0d7ec82e3cafea9b
  - git_url: https://github.com/PennyLaneAI/pennylane-lightning-gpu.git
    git_rev: d82ac5e116a0087b007ab81d48c117cdfa313728

build:
  number: 0
  skip: true  # [(not linux) or (cuda_compiler_version !=  "11.2")]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  # script: export LD_LIBRARY_PATH={{ PREFIX }}/lib && {{ PYTHON }} -m pip install . --no-deps -vv #https://github.com/introlab/rtabmap_ros/issues/131
  missing_dso_whitelist:
    - '*/libcuda.*'  # [linux]
    - '*/libcustatevec.*'  # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - ninja
    - make
  host:
    - {{ pin_compatible('cudatoolkit', max_pin='x', lower_bound='11.2') }} # cudatoolkit >=11.2,<12.0.0
    - cuquantum
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - pip
    - pybind11
    - python
    - setuptools <=64.0.2 # required by cvxpy
    - wheel
  run:
    - cmake              # required by pennylane-lightning-gpu
    - {{ pin_compatible('cudatoolkit', max_pin='x', lower_bound='11.2') }} # cudatoolkit >=11.2,<12.0.0
    - cuquantum
    - ninja              # required by pennylane-lightning-gpu
    - pennylane
    - pip
    - python
    - setuptools <=64.0.2 # required by cvxpy
test:
  imports:
    - pennylane_lightning_gpu
  commands:
    - python -c "import pennylane as qml; qml.about()"
    - pip check
  requires:
    - setuptools <=64.0.2 # version requirement from cvxpy
    - flaky
    - pip

about:
  home: https://docs.pennylane.ai/projects/lightning-gpu/en/latest/
  summary: The PennyLane-Lightning-GPU plugin extends the Pennylane-Lightning state-vector simulator written in C++, and offloads to the NVIDIA cuQuantum SDK for GPU accelerated circuit simulation.
  license: Apache-2.0
  # MIT is pennylane/grouping/graph_colouring.py
  license_file: LICENSE
  doc_url: https://docs.pennylane.ai/projects/lightning-gpu/en/latest/devices.html

extra:
  recipe-maintainers:
    - vincentmr
  feedstock-name: {{ name }}
