{% set name = "numpy-utils" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Serapieum-of-alex/numpy-utils/archive/{{ version }}.tar.gz
  sha256: 3482976079e576cc50a5b756c0072d979f01b4f97e59827308c6b5a5a259e502

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<3.11
    - pip
  run:
    - python >=3.9,<3.11
    - numpy >=1.24.1

test:
  imports:
    - numpy_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Serapieum-of-alex/numpy-utils
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: numpy utility package
  description: |
    Numpy utility package with various functionality to handling numpy array.
  dev_url: https://github.com/Serapieum-of-alex/numpy-utils
  doc_url: https://numpy-utils.readthedocs.io/

extra:
  recipe-maintainers:
    - MAfarrag
