{% set name = "devtools" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/devtools-{{ version }}.tar.gz
  sha256: 6eb7c4fa7c4b90e5cfe623537a9961d1dc3199d8be0981802c6931cd8f02418f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - executing >=1.1.1
    - asttokens >=2.0.0,<3.0.0

test:
  imports:
    - devtools
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python's missing debug print command, and more.
  dev_url: https://github.com/samuelcolvin/python-devtools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
