{% set name = "georouting" %}
{% set version = "0.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 15041e19a0484a177ed22fb6f725855c0efb0e8fafca4132906201ab23a15637

build:
  number: 0
  noarch: python
  entry_points:
    - georouting=georouting.cli:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - geopandas
    - googlemaps
    - igraph
    - osmnx
    - polyline
    - python >=3.6

test:
  imports:
    - georouting
    - georouting.routers
  commands:
    - georouting --help
  requires:
    - pytest >=3

about:
  home: "https://github.com/wybert/georouting"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Geo routing for Python users"
  doc_url: https://wybert.github.io/georouting/
  dev_url: https://github.com/wybert/georouting

extra:
  recipe-maintainers:
    - wybert
