{% set name = "mmgsuite" %}
{% set version = "5.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url: https://github.com/MmgTools/mmg/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bbf9163d65bc6e0f81dd3acc5a51e4a8c47a7fdae849abc26277e01154fe2437

build:
  number: 0
  missing_dso_whitelist:
    - "*/libCommons.so"
    - "*/libElas.so"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - iscd-commons
    - iscd-linearelasticity    
  host:
    - git
    - setuptools-scm
    - cmake
    - make
    - scotch
    - tbb
    - tbb-devel
  run:
    - scotch
    - tbb
    - iscd-commons
    - iscd-linearelasticity

about:
  home: https://www.mmgtools.org/mmg-open-source-consortium
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: 'mmg - Surface and volume remeshers'
  description: |
    open source software for bidimensional and tridimensional surface and volume remeshing
  doc_url: https://www.mmgtools.org/mmg-remesher-try-mmg/mmg-remesher-tutorials
  dev_url: http://www.salome-platform.org/

extra:
  recipe-maintainers:
    - ldallolio
