{% set name = "napari-process-points-and-surfaces" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-process-points-and-surfaces-{{ version }}.tar.gz
  sha256: c3ec2630de2972fb03604b2a5c8b50348e3848a0e1fa949cb53b826822fbee18

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - ipyvtklink
    - napari
    - napari-plugin-engine >=0.1.4
    - napari-time-slicer >=0.4.5
    - napari-tools-menu >=0.1.14
    - napari-workflows >=0.2.3
    - numpy
    - open3d
    - python >=3.7
    - vedo

test:
  imports:
    - napari_process_points_and_surfaces
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-process-points-and-surfaces
  summary: Process and analyze surfaces using open3d and vedo in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
