{% set name = "rapidpe-rift-pipe" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rapidpe_rift_pipe-{{ version }}.tar.gz
  sha256: ee5d6b5116863193637241d5350a9fc5b8d316892c67324e509e9153baa1cf21

build:
  entry_points:
    - rapidpe-rift-pipe = rapidpe_rift_pipe.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
  run:
    - h5py
    - lalsuite
    - matplotlib-base
    - numpy
    - python
    - rapid-pe==0.0.0
    - rift==0.0.15.6

test:
  imports:
    - rapidpe_rift_pipe
  commands:
    - pip check
    - rapidpe-rift-pipe --help
  requires:
    - pip

about:
  home: https://pypi.org/project/rapidpe-rift-pipe/
  summary: Dag submission scripts for rapid pe and rift
  license: GPL-2.0-or-later
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - dwysocki
