{% set name = "rapidpe-rift-pipe" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rapidpe_rift_pipe-{{ version }}.tar.gz
  sha256: a048f86783bb35567d8a247718c198ff6085d2a332f3f365c685d17c408378ff

build:
  entry_points:
    - rapidpe-rift-pipe = rapidpe_rift_pipe.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - matplotlib-base
    - h5py
    - tabulate
    - lalsuite
    - rift >=0.0.15.7, <0.0.15.9
    - rapid-pe ==0.0.6

test:
  imports:
    - rapidpe_rift_pipe
  commands:
    - pip check
    - rapidpe-rift-pipe --help
  requires:
    - pip

about:
  home: https://git.ligo.org/rapidpe-rift/rapidpe-rift-pipe
  summary: Pipeline for running RapidPE and RIFT parameter estimation codes
  license: GPL-2.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - dwysocki
