{% set name = "lpython" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/lcompilers/lpython.git
  git_rev: 7e6c1b905f317a3f384ee4090ae7726d239b25a1
  patches:
    - macos_clock.patch
    - win_tests.patch

build:
  number: 0
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make   # [unix]
    - xeus =2.4.1       # [build_platform != target_platform]
    - llvmdev =15.0.6   # [build_platform != target_platform]
    - xtl               # [build_platform != target_platform]
    - nlohmann_json     # [build_platform != target_platform]
    - cppzmq            # [build_platform != target_platform]
    - zlib              # [build_platform != target_platform]
    - re2c =2.2
    - bison =3.4        # [not win]
    - m2-bison =3.0.4   # [win]
    - xonsh =0.13.4     # [win]

  host:
    - xeus =2.4.1
    - llvmdev =11.1.0   # [osx and x86_64]
    - llvmdev =15.0.7   # [not osx or not x86_64]
    - xtl
    - nlohmann_json
    - cppzmq
    - zlib
  run:
    # xeus breaks abi compatibility in patch versions even though
    # run_exports say otherwise in https://github.com/conda-forge/xeus-feedstock/blob/0896038be810da2944ebcb612e22886815ea691e/recipe/meta.yaml#L18
    - {{ pin_compatible("xeus", max_pin="x.x.x") }}  # [win]
    - zstd =1.5.2  # [x86_64]

test:
  requires:
    - jupyter
  commands:
    - test -f ${PREFIX}/bin/lpython  # [unix]
    - if not exist %LIBRARY_PREFIX%\bin\lpython.exe exit 1  # [win]
    - lpython --help
    - lpython --version
    - jupyter kernelspec list --json
      # This fails if the `fortran` spec is not installed
    - jupyter kernelspec remove -f fortran

about:
  home: https://lpython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Modern interactive LLVM-based Python compiler
  dev_url: https://github.com/lcompilers/lpython.git

extra:
  recipe-maintainers:
    - certik
