{% set name = "nomad" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hashicorp/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f7b67e83134257f5a101f7bd6050d67d055c4002ee49f154539a0e61b946c755

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }} =1.18.5
    - sysroot_linux-64 2.17  # [linux64]
    - make
    - yarn
    - go-licenses

test:
  commands:
    - nomad -h

about:
  home: https://nomadproject.io
  license: MPL-2.0
  license_file: LICENSE
  license_file: license-files/
  summary: Nomad is an easy-to-use, flexible, and performant workload orchestrator that can deploy a mix of microservice, batch, containerized, and non-containerized applications.
  doc_url: https://developer.hashicorp.com/nomad/docs
  dev_url: https://github.com/hashicorp/{{ name }}

extra:
  recipe-maintainers:
    - jonashaag
