{% set name = "nomad" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hashicorp/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f7b67e83134257f5a101f7bd6050d67d055c4002ee49f154539a0e61b946c755

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }} =1.18.5
    - make
    - yarn

test:
  commands:
    - nomad -h

about:
  home: https://github.com/hashicorp/{{ name }}
  license: MPL-2.0
  license_file: LICENSE
  summary: Nomad is an easy-to-use, flexible, and performant workload orchestrator that can deploy a mix of microservice, batch, containerized, and non-containerized applications.

extra:
  recipe-maintainers:
    - jonashaag
