{% set name = "openeo" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Open-EO/openeo-python-client/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1fe6339a960216bb61083f356bdc94063337df241253fff723f9006ac1fa20a2

build:
  number: 0
  #skip: True  # [not win]" to limit to Windows.
  skip: True  # [py<35]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
    - deprecated
    - geopandas
    - graphviz
    - h5netcdf
    - matplotlib
    - numpy
    - pandas
    - pytest-runner
    - requests
    - shapely
    - xarray
  run:
    - python
    - deprecated
    - geopandas
    - graphviz
    - h5netcdf
    - matplotlib
    - numpy
    - pandas
    - requests
    - shapely
    - xarray

test:
  imports:
    - openeo
  requires:
    - pip
    - pytest-runner
    - mock
    - requests-mock
  source_files:
    - tests
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/Open-EO/openeo-python-client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python Client Library for the openEO API. Allows you to interact with openEO backends from your own (local) Python environment.'

extra:
  recipe-maintainers:
    - sebastian-luna-valero
