{% set name = "openeo" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Open-EO/openeo-python-client/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1487da00a176db5055c34d6bbc0bbe41efd06819d65e34bc1395eef35608d835
#  git_url: https://github.com/Open-EO/openeo-python-client.git

build:
  number: 0
#  skip: True  # [py<35 or win]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - deprecated >=1.2.12
    - numpy >=1.17.0
    - pandas >0.20.0
    - requests >=2.26.0
    - shapely >=1.6.4
    - xarray >=0.12.3

test:
  imports:
    - openeo
  requires:
    - pip
    - pytest >=4.5.0
    - pytest-runner
    - matplotlib-base
    - mock
    - requests-mock >=1.8.0
    - h5netcdf
    - geopandas
  source_files:
    - tests
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/Open-EO/openeo-python-client
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python Client Library for the openEO API. Allows you to interact with openEO backends from your own (local) Python environment.'

extra:
  recipe-maintainers:
    - sebastian-luna-valero
    - soxofaan
    - jdries
