{% set name = "fvgp" %}
{% set version = "7.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: url: https://github.com/lbl-camera/fvGP/archive/{{ version }}.tar.gz
  sha256: 6e1f3341ac108ed13c1a440435cde3aac36406512ae0b947aad9889d01103de6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - wheel
    - versioneer
    - pytorch >=1.9.0
    - scipy
    - numpy
    - matplotlib-base
    - dask-core >=2021.6.2
    - distributed >=2021.6.2
    - hgdl ==2.0.6
    - notebook
    - plotly
    - loguru

test:
  imports:
    - fvgp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lbl-camera/fvGP
  summary: Python package for highly flexible function-valued Gaussian processes (fvGP)
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
