{% set name = "AirTrafficSim" %}
{% set version = "0.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/HKUST-OCTAD-LAB/AirTrafficSim/releases/download/{{ version }}/AirTrafficSim-{{ version }}.tar.gz
  url: https://github.com/HKUST-OCTAD-LAB/AirTrafficSim/archive/v{{ version }}.tar.gz
  sha256: 74b4138acdd107f3bbd94a7e4eeb7b6093be440f6868f4185e414c6ba27dfce9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas
    - Flask
    - Flask-SocketIO
    - Eventlet
    - cartopy
    - cdsapi
    - xarray
    - openap

test:
  imports:
    - airtrafficsim
  requires:
    - pip

about:
  home: https://github.com/HKUST-OCTAD-LAB/AirTrafficSim
  summary: 'A web-based air traffic simulation software written in Python and javascript.'
  description: |
    AirTrafficSim is a web-based air traffic simulation software written in Python and javascript. 
    It is designed to visualize historical and research data, perform microscopic studies of air traffic movement with the integration of a historical weather database, and evaluate the performance of ATM algorithms.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://hkust-octad-lab.github.io/AirTrafficSim/

extra:
  recipe-maintainers:
    - kyfrankie
