{% set name = "iscd-mshdist" %}
{% set version = "0.0.0rc0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # there are no tagged releases which so using archives of specific commits
  url: https://github.com/ISCDtoolbox/Mshdist/archive/19d59d8375fc967d9e30e1a7c71756c538d692c1.zip
  sha256: 3f2febb09734359f6a0ef390b4650a03f0eb2931c5efd67e016f1c98bf083e76

build:
  number: 0
  skip: true  # [py2k or win or osx] # "CMakeLists.txt": invalid command code C && Cannot open include file: 'pthread.h': No such file or directory 
  missing_dso_whitelist:
    - "*/libCommons.so"
    - "*/libCommons.dylib"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - iscd-commons
  host:
    - cmake
    - make  # [not win]
    - jom  # [win]

test:
  commands:
    - test -f $PREFIX/bin/mshdist  # [unix]

about:
  home: https://iscd.sorbonne-universite.fr/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: 'ISCD - mshdist'
  description: |
    mshdist is a simple algorithm to generate the signed distance function to given objects in two and three space dimensions.
  doc_url: https://github.com/ISCDtoolbox/Mshdist/tree/master/documentation
  dev_url: https://github.com/ISCDtoolbox/Mshdist.git

extra:
  recipe-maintainers:
    - ldallolio
    - cnrdn
    - fbordeu
