{% set name = "iscd-mshdist" %}
{% set version = "1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url: https://github.com/ISCDtoolbox/Mshdist/archive/refs/heads/master.zip
  sha256: 0bf798b456fce7a017aad0f5b96e1c88abfec287c21a74dd371d2818d5b725e5

build:
  number: 0
  skip: true  # [py2k or win or osx] # "CMakeLists.txt": invalid command code C && Cannot open include file: 'pthread.h': No such file or directory 
  missing_dso_whitelist:
    - "*/libCommons.so"
    - "*/libCommons.dylib"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - iscd-commons
  host:
    - cmake
    - make  # [not win]
    - jom  # [win]

about:
  home: https://iscd.sorbonne-universite.fr/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: 'ISCD - mshdist'
  description: |
    mshdist is a simple algorithm to generate the signed distance function to given objects in two and three space dimensions.
  doc_url: https://github.com/ISCDtoolbox/Mshdist/tree/master/documentation
  dev_url: https://github.com/ISCDtoolbox/Mshdist.git

extra:
  recipe-maintainers:
    - ldallolio
