{% set name = "jupyterlite-pyodide-kernel" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlite_pyodide_kernel-{{ version }}.tar.gz
  sha256: 2f9c61104ad61f1c4fa10af4ff36bf3c5682db353bf07c56548e0aa03bf7a0fa

build:
  entry_points:
    - jupyter-piplite = jupyterlite_pyodide_kernel.app:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.4.0
    - jupyterlab >=3.5.3,<3.6
    - pip
  run:
    - python >=3.8
    - jupyterlite-core >=0.1.0,<0.2.0
    - pkginfo

test:
  commands:
    - pip check
    - jupyter-piplite --help
  requires:
    - pip

about:
  home: https://github.com/jupyterlite/pyodide-kernel
  summary: Python kernel for JupyterLite powered by Pyodide
  dev_url: https://github.com/jupyterlite/pyodide-kernel
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtpio
