{% set name = "intake-odbc" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intake/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: e106e2213a0d6e169f452fcd62c40f321d89755926ec28ff8e08bde572d24491

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - intake
    - turbodbc
    - pyarrow
    - pandas

test:
  imports:
    - intake_odbc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/intake/intake-odbc
  summary: ODBC Plugin for Intake
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martindurant
    - blakerosenthal
