{% set name = "ecodata" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jemissik/ecodata/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bf71254d286b8b775ab947f0b1c8e85dad07206961abb3f83442db70725974e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python >3.8
    - cartopy
    - geopandas
    - matplotlib
    - pandas
    - shapely <2.0
    - xarray
    - dask
    - netCDF4
    - bottleneck
    - cfgrib
    - rasterio
    - numpy <1.24
    - rioxarray
    - hvplot
    - panel
    - datashader
    - geoviews
    - geocube
    - gdown
    - ffmpeg

test:
  imports:
    - ecodata

about:
  summary: |
    Tools to access and process remote sensing and other environmental
    data products and prepare them for further use along with animal movement data
  home: https://github.com/jemissik/ecodata
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jemissik
    - madeline-scyphers
