{% set data = load_setup_py_data() %}
{% set name = "ecodata" %}

package:
  name: {{ name|lower }}
  version: {{ data['version'] }}

source:
  url: https://github.com/jemissik/ecodata/archive/refs/tags/v{{ data['version'] }}.tar.gz
  sha256: 8026275d2a39619c1d45ee3bae4eede5324de85ba1213a686456ed550db6e002

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python {{ data['python_requires'] }}
    {% for dep in data.get('install_requires',{}) %}
    - {{ dep }}
    {% endfor %}

test:
  imports:
    - ecodata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jemissik/ecodata
  license: MIT
  license_file: LICENSE


extra:
  recipe-maintainers:
    - jemissik
    - madeline-scyphers
