
{% set name = "priori" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/ohsu-comp-bio/regulon-enrichment/archive/refs/tags/v0.1.0.tar.gz
  sha256: 846f69b8aa2b9065ae7d5011b9450b9f59217365e960f02c19169ca4d7fcddc8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip

  run:
    - python
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - tqdm
    - dill

test:
  imports:
    - priori

  source_files:
    - priori/tests/*.py

about:
  home: https://github.com/ohsu-comp-bio/regulon-enrichment
  summary: 'Predicting transcription factor activity using prior information'
  license: GNU GENERAL PUBLIC LICENSE
  description: Priori predicts transcription factor activity from RNA sequencing data using prior, literature-supported regulatory relationship information
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - yasharw