{% set name = "priori" %}
{% set version = "1.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/ohsu-comp-bio/regulon-enrichment/archive/refs/tags/v1.0.2.tar.gz
  sha256: 484ea64744946b82fea8d9e232af3c090ff9eaac11308660abf67510f155a636

build:
  number: 0
  entry_points:
    - priori=priori.priori:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python ==3.6.15
    - dill ==0.3.1.1
    - numpy ==1.17.3
    - pandas ==0.25.3
    - pip
    - setuptools
    - scikit-learn ==0.21.3
    - scipy ==1.5.2
    - tqdm ==4.38.0

  run:
    - python ==3.6.15
    - dill ==0.3.1.1
    - numpy ==1.17.3
    - pandas ==0.25.3
    - scikit-learn ==0.21.3
    - scipy ==1.5.2
    - tqdm ==4.38.0

test:
  imports:
    - data
    - priori
    - priori.features
    - priori.regulon
  commands:
    - priori --help

about:
  home: "https://github.com/ohsu-comp-bio/regulon-enrichment"
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: "Priori predicts transcription factor activity from RNA sequencing data using prior, literature-supported regulatory relationship information"

extra:
  recipe-maintainers:
    - yasharw
