
{% set name = "priori" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/ohsu-comp-bio/regulon-enrichment/archive/refs/tags/v0.1.0.tar.gz
  sha256: 99adc74f9edff50ba834b3048f2641302793b4911b2ea9d00286db1157122be5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - tqdm
    - dill

test:
  imports:
    - priori

  source_files:
    - priori/tests/*.py

about:
  home: https://github.com/ohsu-comp-bio/regulon-enrichment
  summary: 'Predicting transcription factor activity using prior information'
  license: GPL-2.0-or-later
  license_family: GPL
  description: Priori predicts transcription factor activity from RNA sequencing data using prior, literature-supported regulatory relationship information
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - yasharw
