{% set name = "mumps-aster" %}
{% set version = "5.1.2" %}
{% set sha256 = "7d9e42c14daaad76f861c3d8ea7895e6fd5557f698938fe9a14e14f5e9cd7c31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}_{{ version }}-aster6.tar.gz
  url: https://sourceforge.net/code-snapshots/hg/p/pr/prereq/mumps/prereq-mumps-b9429561b76ca8c23fc99198ca8d4c968c44e147.zip
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [osx or win or (python_impl == 'pypy')]
  detect_binary_files_with_prefix: True

requirements:
  build:
    - gcc 8  # [linux]
    - gxx 8  # [linux]
    - gfortran 8  # [linux]
    - sysroot_linux-64 =2.17
  host:
    - make
    - numpy 1.20
    - metis-aster 5.1    
    - libgomp
    - scotch
    - libblas
    - liblapack
    - zlib          

  run:
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - {{ pin_compatible('scotch', max_pin='x.x') }}  
    - libgomp    
    - {{ pin_compatible('metis-aster', max_pin='x.x') }}

test:
    commands:
        #- test -f "${PREFIX}/mumps-aster/lib/libsmumps{SHLIB_EXT}"
        #- test -f "${PREFIX}/mumps-aster/lib/libdmumps${SHLIB_EXT}"
        #- test -h "${PREFIX}/mumps-aster/lib/libcmumps${SHLIB_EXT}"
        #- test -h "${PREFIX}/mumps-aster/lib/libzmumps${SHLIB_EXT}"
        #- test -f "${PREFIX}/mumps-aster/lib/libmumps_common${SHLIB_EXT}"
        #- test -h "${PREFIX}/mumps-aster/lib/libpord${SHLIB_EXT}"
        #- test -h "${PREFIX}/mumps-aster/lib/libmpiseq${SHLIB_EXT}"
        - test -f "${PREFIX}/mumps-aster/include_seq/mpi.h"
        - test -f "${PREFIX}/mumps-aster/include_seq/mpif.h"

about:
    description: 'MUMPS (MUltifrontal Massively Parallel Solver) is a package for
        solving
        systems of linear equations of the form Ax = b, where A is a square sparse
        matrix that can be either unsymmetric, symmetric positive definite, or
        general symmetric, on distributed memory computers. MUMPS implements a
        direct method based on a multifrontal approach which performs a Gaussian
        factorization. Modified for long integers
        '
    doc_url: http://mumps.enseeiht.fr/index.php?page=doc
    src_url: https://sourceforge.net/p/prereq/mumps
    home: http://mumps.enseeiht.fr/
    license: CeCILL-C
    license_file: LICENSE
    summary: 'MUMPS: a parallel sparse direct solver'

extra:
  recipe-maintainers:
    - ldallolio
