{% set name = "lofo-importance" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lofo-importance-{{ version }}.tar.gz
  sha256: 4dbee1e974ae7d93c5a68f3feae887ddc6d1009490e664da582f78c642e70d49

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - lightgbm
    - networkx
    - numpy >=1.17.3
    - pandas
    - scikit-learn >=0.20.3
    - scipy
    - tqdm

test:
  imports:
    - lofo_importance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aerdem4/lofo-importance
  summary: Leave One Feature Out Importance
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/aerdem4/lofo-importance
  doc_url: https://github.com/aerdem4/lofo-importance/blob/master/README.md

extra:
  recipe-maintainers:
    - melonhead901
