# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe
# If your package is python based, we recommend using Grayskull to generate it instead:
# https://github.com/conda-incubator/grayskull

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "jupyterlab_rise" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db03142fe386c8f07265970e0bbca752d2b851de994062b4e6f98af87893784a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling>=1.4.0
    - jupyterlab>=3.4.7,<4.0.0
    - hatch-nodejs-version
  run:
    - python >=3.7
    - jupyterlab>=3.0.0,<4.0.0

test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - jupyterlab_rise
  # For python packages, it is useful to run pip check. However, sometimes the
  # metadata used by pip is out of date. Thus this section is optional if it is
  # failing.
  requires:
    - pip
  commands:
    - pip check
    - jupyter server extension list 2>&1 | grep -ie "jupyterlab_rise.*OK"
    - jupyter labextension list 2>&1 | grep -ie "jupyterlab-rise.*OK"
    - python -m jupyterlab.browser_check --no-chrome-test

about:
  home: https://github.com/jupyterlab-contrib/rise
  summary: 'RISE: "Live" Reveal.js JupyterLab Slideshow extension.'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fcollonval
