{% set name = "parallel-ssh" %}
{% set version = "2.6.0.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/parallel-ssh-{{ version }}.tar.gz
  sha256: 7308a4cec44b69b9361d3cf473da94908064665eb04ca4cd718a6e4e177b3dbd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - gevent >=1.3.0
    - python
    - ssh-python >=0.9.0
    - ssh2-python >=0.22.0

test:
  imports:
    - pssh
    - pssh.clients
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ParallelSSH/parallel-ssh
  summary: Asynchronous parallel SSH library
  license: GPL-2.0
  license_file: COPYING

extra:
  recipe-maintainers:
    - MattChanTK
