{% set name = "rapdidcheck" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


# use github url for now since
# there are no tags / releases yet
source:
  git_url: https://github.com/emil-e/rapidcheck
  git_rev: 1505cbbce733bde3b78042cf2e9309c0b7f227a2
  git_depth: 1

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake

test:
  commands:
    - test -e ${PREFIX}/include/rapidcheck/rapidcheck.h  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\rapidcheck\rapidcheck.h (exit 1)  # [win]

about:
  home: https://github.com/emil-e/rapidcheck
  summary: 'RapidCheck is a C++ framework for property based testing inspired by QuickCheck and other similar frameworks.'
  description: |
    RapidCheck is a C++ framework for property based testing inspired by QuickCheck and other similar frameworks. 
    In property based testing, you state facts about your code that given certain precondition should always be true.
    RapidCheck then generates random test data to try and find a case for which the property doesn't hold. 
    If such a case is found, RapidCheck tries to find the smallest case (for some definition of smallest) 
    for which the property is still false and then displays this as a counterexample. 
    For example, if the input is an integer, RapidCheck tries to find the smallest integer for which the property is false.

  license: BSD 2-Clause "Simplified" License
  license_family: BSD
  license_file: LICENSE.md
  doc_url: https://github.com/emil-e/rapidcheck/blob/master/doc/user_guide.md
  dev_url: https://github.com/emil-e/rapidcheck

extra:
  recipe-maintainers:
    - DerThorsten
