{% set name = "aster" %}
{% set version = "14.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Offical release downloads from https://www.code-aster.org/spip.php?rubrique21
  # are packaged will tars of all dependencies, so instead download code only
  # from official Sourceforge snapshot. The Sourceforge snapshot download page
  # https://sourceforge.net/p/codeaster/src/ci/14.6.0/tarball redirects to a
  # URL with the commit hash instead of version tag:
  url: https://sourceforge.net/code-snapshots/hg/c/co/codeaster/src/codeaster-src-b3490fa3b76cfbb7127dabe783c10aa7959fe8e3.zip
  sha256: 3f6215f9ac15ca0ea7a80f7835abec5ddd515820824d2c9c987b18b47970c496

build:
  number: 0
  skip: true  # [py2k or osx or win]
  detect_binary_files_with_prefix: True

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - sysroot_linux-64 =2.17
  host:
    - make
    - bison
    - flex
    - swig
    - gettext
    - tk
    - boost {{ boost }}
    - python {{ python }}
    - numpy {{ numpy }}
    - mfront 3.2.1
    - libgomp
    - libmed {{ libmed }}
    - hdf5 {{ hdf5 }}
    - scotch {{ scotch }}
    - libblas
    - liblapack
    - zlib

  run:
    - python {{ python }}
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - {{ pin_compatible('boost', max_pin='x.x') }}
    - {{ pin_compatible('libmed', max_pin='x.x') }}
    - {{ pin_compatible('hdf5', max_pin='x.x') }}
    - {{ pin_compatible('scotch', max_pin='x.x') }}
    - libgomp


test:
  imports:
     - asrun

about:
  home: https://www.code-aster.org
  license: GPL-3.0-only
  license_family: GPL
  license_file: ./LICENSE.txt
  summary: 'Code_Aster : a finite element solver'
  description: >
    Code_Aster offers a full range of multiphysical analysis and modelling
    methods that go well beyond the standard functions of a thermomechanical
    calculation code: from seismic analysis to porous media via acoustics,
    fatigue, stochastic dynamics, etc..
  doc_url: https://www.code-aster.org/V2/doc/default/en/index.php?man=commande
  dev_url: https://sourceforge.net/projects/codeaster/

extra:
  recipe-maintainers:
    - ldallolio
