{% set name = "bfio" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bfio-{{ version }}.tar.gz
  sha256: 963a56aed17cf0fcbcac3995daf61dd75b8d68d8358b144003d79cf17dce16fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - imagecodecs >=2021.2.26
    - lxml
    - numpy >=1.20.1
    - ome-types >=0.2.10
    - python >=3.6
    - tifffile >=2021.8.30

test:
  imports:
    - bfio
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - napari

about:
  home: https://pypi.org/project/bfio/
  summary: Simple reading and writing classes for tiled tiffs using Bioformats.
  dev_url: https://github.com/labshare/bfio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Nicholas-Schaub
    - goanpeca
    - jaimergp
