{% set name = "openphase" %}
{% set version = "1.0.0" %}
{% set versionstr = version.replace('.', '_') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://openphase.rub.de/assets/download/OpenPhase-V{{ versionstr }}.zip
  sha256: 2b3a0c466fb4a1014ea131c2b8ea7c519f9278eba73d6fcb361b7bdb4fd494e9

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - fftw
    - {{ mpi }}
  run:

test:
  commands:
    - LinearSystemSolver --help

about:
  home: https://openphase.rub.de/
  summary: 'OpenPhase is based on the multi-phase-field model as developed by Steinbach and his co-workers'
  description: |
    OpenPhase is an open-source C++ software project started in 2008 at 
    the Interdisciplinary Centre for Advanced Materials Simulation, 
    Ruhr-Universität Bochum, Germany. OpenPhase is dedicated to 
    investigating microstructure evolution in materials undergoing 
    first-order phase transformations, capillarity-driven coarsening 
    processes, or a combination of both. Also you may embed the 
    simulation into a macroscopic process simulation which determine 
    boundary conditions on the micro domain, heat fluxed, mechanical 
    loading or others.
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  doc_url: https://openphase.rub.de/documentation/index.html
  dev_url: https://openphase.rub.de/

extra:
  recipe-maintainers:
    - jan-janssen
