{% set name = "git-delta" %}
{% set version = "0.15.1" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/dandavison/delta/archive/refs/tags/{{ version }}.tar.gz
  sha256: b9afd2f80ae1d57991a19832d6979c7080a568d42290a24e59d6a2a82cbc1728

build:
  number: 0

script_env:
    - LDFLAGS="-Wl,-rpath-link,$PREFIX/lib"
    - CFLAGS="-L$PREFIX/lib"

run_exports:
  libs:
    - libgcc_s.so.1

requirements:
  build:
    - {{ compiler('rust') }}
  run:
    - zlib
    - libgcc  # [linux]

test:
  commands:
    - delta --version

about:
  home: https://github.com/dandavison/delta
  license: MIT
  license_family: MIT
  license_file: LICENCE.txt
  summary: Syntax-highlighting pager for git and diff output.
  description: |
    Delta is a viewer for git and diff output. It displays changes in a more
    structured way, highlighting syntax and supporting background color for
    visual diffs. Delta is an evolution of the lesspipe.sh script.

extra:
  recipe-maintainers:
    - YYYasin19
