{% set name = "mitmproxy_wireguard" %}
{% set version = "0.1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mitmproxy_wireguard-{{ version }}.tar.gz
  sha256: f2283d5167fe939b83290804e7a3305613f8c715c39d8c82f08e1ae93f235b3c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - rust
    - maturin
  host:
    - maturin >=0.13,<0.14
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - mitmproxy_wireguard
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mitmproxy-wireguard/
  summary: WireGuard interface for mitmproxy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AdrianFreundQC
    - freundTech
