{% set name = "brie" %}
{% set version = "1.0.0b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mcflugen/brie/archive/v{{ version }}.tar.gz
  sha256: ba949cd930d60408d71587c1490950e21f4a3bf5d512151a53d789e641d8ae8f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - bmipy
    - numpy
    - pyyaml
    - scipy
  run:
    - python
    - bmipy
    - numpy
    - pyyaml
    - scipy

test:
  imports:
    - brie
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/UNC-CECL/brie
  summary: 'The Barrier Inlet Environment (BRIE) Model'
  description: |
    This is the python version of the BarrieR Inlet Envrionment (BRIE) model written
    by Jaap Nienhuis and Jorge Lorenzo Trueba.
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  doc_url: https://github.com/UNC-CECL/brie
  dev_url: https://github.com/UNC-CECL/brie

extra:
  recipe-maintainers:
    - mcflugen
    - anardek
