{% set name = "gettsim" %}
{% set version = "0.6.0a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gettsim-{{ version }}.tar.gz
  sha256: 02b165269795caa635131d11e73a434e4145ed9a70ec2630af00532a2fbb27a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.0
    - pip
  run:
    - python >=3.9
    - dags
    - networkx
    - numpy
    - numpy_groupies
    - pandas
    - plotly
    - pygments
    - pygraphviz
    - pytest

test:
  imports:
    - gettsim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iza-institute-of-labor-economics/gettsim
  summary: The German Taxes and Transfers SIMulator
  license: AGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmgaudecker
