{% set name = "libebm" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/interpretml/interpret/archive/200f9c3f08da6f17bdbeaee0e3285a2458f92f18.tar.gz
  # curl -sL https://github.com/interpretml/interpret/archive/200f9c3f08da6f17bdbeaee0e3285a2458f92f18.tar.gz | openssl sha256
  sha256: e61f014fb24f0dae58e4099f6affd15713928e66eab5078892e546b704920b8b
  # url: https://github.com/interpretml/interpret/archive/v{{ version }}.tar.gz

build:
  number: 0
  script: .\build.bat && copy .\staging\lib_ebm_native_win_x64.dll "%PREFIX%\Library\bin\libebm.dll"  # [win]
  script: /bin/sh ./build.sh && cp ./staging/lib_ebm_native_linux_x64.so "$PREFIX/lib/libebm.so"  # [linux]
  script: /bin/sh ./build.sh && cp ./staging/lib_ebm_native_mac_x64.dylib "$PREFIX/lib/libebm.dylib"  # [osx]

test:
  commands:
    where libebm.dll  # [win]
    # IF NOT EXIST "%PREFIX%\Library\bin\libebm.dll" EXIT /B 1  # [win]
    [ -e "$PREFIX/lib/libebm.so" ]  # [linux]
    [ -e "$PREFIX/lib/libebm.dylib" ]  # [osx]

about:
  home: https://github.com/interpretml/interpret
  summary: Fit interpretable machine learning models. Explain blackbox machine learning.
  description: |
    Shared native library for **the** interpret package.

    https://github.com/interpretml/interpret
  license: MIT
  license_file: LICENSE
  doc_url: https://interpret.ml/docs/getting-started
  dev_url: https://interpret.ml/docs/installation-guide.html

extra:
  recipe-maintainers:
    - paulbkoch
