# name for conda package (i.e. `conda install -c conda-forge <project_name>`)
{% set project_name = "evalhyd-cpp" %}
# name for C++ library
{% set library_name = "evalhyd" %}
{% set version = "0.1.0-rc.2" %}
{% set sha256 = "db997de41dd2c899bf10d795290ef00381623bc7da14f3b963268a039f31567c" %}

package:
  name: {{ project_name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/{{ project_name }}/-/archive/v{{ version }}/{{ project_name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true                  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make                    # [unix]
    - ninja                   # [win]
  host:
    - xtl >=0.7.5
    - xtensor >=0.24.6

test:
  commands:
    - test -d ${PREFIX}/include/evalhyd                                                    # [unix]
    - test -f ${PREFIX}/include/evalhyd/evald.hpp                                          # [unix]
    - test -f ${PREFIX}/include/evalhyd/evalp.hpp                                          # [unix]
    - test -f ${PREFIX}/lib/cmake/EvalHyd/EvalHydConfig.cmake                              # [unix]
    - test -f ${PREFIX}/lib/cmake/EvalHyd/EvalHydConfigVersion.cmake                       # [unix]
    - if not exist %LIBRARY_PREFIX%\include\evalhyd\evald.hpp (exit 1)                     # [win]
    - if not exist %LIBRARY_PREFIX%\include\evalhyd\evalp.hpp (exit 1)                     # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\EvalHyd\EvalHydConfig.cmake (exit 1)         # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\EvalHyd\EvalHydConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://hydrogr.github.io/evalhyd
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENCE.rst
  summary: A C++ library to evaluate streamflow predictions
  description: |
    A header-only C++ library to evaluate deterministic and 
    probabilistic streamflow predictions
  doc_url: https://hydrogr.github.io/evalhyd/cpp
  dev_url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/{{ project_name }}

extra:
  recipe-maintainers:
    - ThibHlln
