# name for conda package (i.e. `conda install -c conda-forge <project_name>`)
{% set project_name = "evalhyd-cpp" %}
# name for C++ library
{% set library_name = "evalhyd" %}
{% set version = "0.1.0" %}
{% set sha256 = "e2adafda65dd9a8f9fb2fee8ab645d747d39da7a6dd69ed3553dc35da1f2c936" %}

package:
  name: {{ project_name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/{{ project_name }}/-/archive/v{{ version }}/{{ project_name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true                  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make                    # [unix]
  host:
    - xtl >=0.7.5
    - xtensor >=0.24.6

test:
  commands:
    - test -d ${PREFIX}/include/evalhyd  # [unix]
    - test -f ${PREFIX}/include/evalhyd/evald.hpp  # [unix]
    - test -f ${PREFIX}/include/evalhyd/evalp.hpp  # [unix]
    - test -f ${PREFIX}/share/cmake/EvalHyd/EvalHydConfig.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\evalhyd\evald.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\include\evalhyd\evalp.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\EvalHyd\EvalHydConfig.cmake (exit 1)  # [win]

about:
  home: https://hydrogr.github.io/evalhyd
  license: GPL-3
  license_family: GPL
  license_file: LICENCE
  summary: A C++ library to evaluate streamflow predictions
  description: |
    A header-only C++ library to evaluate deterministic and 
    probabilistic streamflow predictions
  doc_url: https://hydrogr.github.io/evalhyd/cpp
  dev_url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/{{ project_name }}

extra:
  recipe-maintainers:
    - ThibHlln
