# name for conda package (i.e. `conda install -c conda-forge <project_name>`)
{% set project_name = "evalhyd-cpp" %}
# name for C++ library
{% set library_name = "evalhyd" %}
{% set version = "0.0.1" %}
{% set sha256 = "963b40349510ee8d96a9b245ce51d493a132c5298f796619501842cffde8bd07" %}

package:
  name: {{ project_name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/{{ project_name }}/-/archive/v{{ version }}/{{ project_name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true                  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make                    # [unix]
  host:
    - xtl >=0.7.5
    - xtensor >=0.24.6

about:
  home: https://hydrogr.github.io/evalhyd
  license: GPL-3
  license_family: GPL
  license_file: LICENCE
  summary: A C++ library to evaluate streamflow predictions
  description: |
    A header-only C++ library to evaluate deterministic and 
    probabilistic streamflow predictions
  doc_url: https://hydrogr.github.io/evalhyd/cpp
  dev_url: https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/{{ project_name }}

extra:
  recipe-maintainers:
    - ThibHlln
