{% set name = "cuda-cupti" %}
{% set version = "12.0.90" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_cupti/{{ platform }}/cuda_cupti-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 3c93a6a8c5eab3a56c1a0a514c0ac7d374807c70a9551155f089588b6c5e1d10  # [linux64]
  sha256: bbabb508eb4fb0f9d98ac3ab4a40d0278de41cef95139c1bfe6436b716dd6cfc  # [ppc64le]
  sha256: 33b3b06cf9838fa3289c7e40f143a8f58b941ccad93f9d0640a29bb83aa2152e  # [aarch64]
  sha256: b65a34a3715e3ef2b835bdd36c43b21c20800325be1eda1e84ad4d80ee837c92  # [win]

build:
  number: 0
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}

outputs:
  - name: cuda-cupti
    requirements:
      run:
        - cuda-version =12.0
    files:
      - lib/*.so.*            # [linux]
      - targets/*/lib/*.so.*  # [linux]
      - Library\lib\*.dll     # [win]

  - name: cuda-cupti-dev
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
      run:
        - cuda-cupti >={{ version }}
        - cuda-version =12.0
    files:
      - lib/*.so               # [linux]
      - targets/*/lib/*.so     # [linux]
      - include                # [linux]
      - targets/*/include      # [linux]
      - samples                # [linux]
      - doc                    # [linux]
      - Library\include        # [win]
      - Library\lib\*.lib      # [win]
      - Library\samples        # [win]
      - Library\doc            # [win]

  - name: cuda-cupti-static
    build:
      skip: True                        # [not linux]
    requirements:
      run:
        - cuda-cupti >={{ version }}
        - cuda-version =12.0
    files:
      - lib/*static.a
      - targets/*/lib/*static.a

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Provides libraries to enable third party tools using GPU profiling APIs.
  description: |
    Provides libraries to enable third party tools using GPU profiling APIs.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - adibbley
