{% set name = "eumdac" %}
{% set version = "2.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 6fe0ce386e035a2c7ebff9697590585d8903f29a94a3bc03ead52b49123343ff

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - pip
    - python
    - requests >=2.5.0
    - pyyaml
  run:
    - python
    - requests >=2.5.0
    - pyyaml

test:
  imports:
    - eumdac

about:
  home: https://eumetsatspace.atlassian.net/wiki/spaces/EUMDAC/overview
  license: MIT
  license_file: LICENSE.txt
  summary: EUMETSAT Data Access Client
  description: EUMDAC is the EUMETSAT Data Access Client. It provides simple access to the EUMETSAT data from a variety of satellite missions. As a Python library, it comes with many methods and helpers to use EUMETSATs APIs and services, like Data Store and Data Tailor. It also provides a variety of useful command-line utilities for data search, translation and processing.
  doc_url: https://eumetsatspace.atlassian.net/wiki/spaces/EUMDAC/overview
  dev_url: https://gitlab.eumetsat.int/eumetlab/data-services/eumdac

extra:
  recipe-maintainers:
  # GitHub IDs for maintainers of the recipe.
    - NiklasJordan
    - rafadelahoz