{% set name = "zstash" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/zstash/archive/v{{ version }}.tar.gz
  sha256: 16d4169dcf49057ac86fb78410bffbc9ceba7680f73d4f88659992c18376cb63

build:
  entry_points:
    - zstash=zstash.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - six ==1.16.0
    - globus-sdk <4.0.0,>=3.0.0
    - fair-research-login ==0.2.6

test:
  imports:
    - zstash
  commands:
    - pip check
    - zstash --help
  requires:
    - pip

about:
  home: https://github.com/E3SM-Project/zstash
  summary: 'Long term HPSS archiving tool for E3SM'
  license: Unlicense AND BSD-3-Clause
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - mahf708
    - xylar
    - tomvothecoder
    - forsyth2
    - chengzhuzhang
