{% set name = "gmpacket" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gmpacket-{{ version }}.tar.gz
  sha256: f7249f6b45207aa7f6ec291bc510f41ac20e78608215943de2f1194587ed97af

build:
  entry_points:
    - gmpformat = gmpacket.bin.gmpformat:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<=3.11
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - cython >=0.29.23
    - numpy
    - pip
  run:
    - python >=3.6,<=3.11
    - pandas >=1.4.0
    - pydantic >=1.10.0
    - schema

test:
  imports:
    - gmpacket
  commands:
    - pip check
    - gmpformat --help
  requires:
    - pip

about:
  home: https://github.com/SCEDC/ground-motion-packet
  summary: ANSS Ground Motion Packet
  license: LPL-1.02
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
