{% set name = "fsl-pipe" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fsl-pipe-{{ version }}.tar.gz
  sha256: c8071953f27c11544fc5a17d218abfab86560f49eadce66ef68ee51c507e237d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.6
    - file-tree
    - xarray
    - dask-core
    - fslpy
    - loguru
    - fsl-sub
    - python-graphviz

test:
  imports:
    - fsl_pipe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.fmrib.ox.ac.uk/ndcn0236/fsl-pipe
  summary: Declative pipelines based on Filetrees
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichielCottaar
