jobs:
- job: linux_64
  condition: not(eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 360
  steps:
  - script: |
      # sudo pip install --upgrade pip
      sudo pip install setuptools shyaml
    displayName: Install dependencies

  - script: |
      set -e

      # make sure there is a package directory so that artifact publishing works
      mkdir -p build_artifacts/{noarch,linux-64}/

      export CI=azure
      export CONFIG=linux64
      export DOCKER_IMAGE=quay.io/condaforge/linux-anvil-cos7-x86_64
      export AZURE=True
      .scripts/run_docker_build.sh

    displayName: Run docker build
    name: linux_64_build

  - publish: build_artifacts/linux-64/
    artifact: conda_pkgs_linux

  - publish: build_artifacts/noarch/
    artifact: conda_pkgs_noarch
