{% set name = "neo4jsbml" %}
{% set version = "0.10.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 172d8ab08cc9b4c40eca3a3b9871727fb1feec635ea368630e3e3456bfd11708

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  build:
    - pip
    - python >= 3.8
    - pyyaml
    - setuptools
  host:
    - python >= 3.8
  run:
    - python-libsbml
    - neo4j-python-driver
    - sphinx
    - sphinx_rtd_theme

test:
  imports:
    - {{ name }}
  commands:
    - {{ name }} --help # [not win]
    - python -m {{ name }} --help # [win]

about:
  home: https://github.com/brsynth/{{ name }}
  summary: Import SBML file into Neo4j
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - guillaume-gricourt
    - tduigou
