{% set name = "gocart" %}
{% set version = "0.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 0c2a8b73f846c2b3a30bb7760c53492eb39335ff069b3337eaba1b9bcd5e19a1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - fundamentals
    - python >=3.9
    - pyyaml

test:
  imports:
    - gocart

about:
  home: https://github.com/thespacedoctor/gocart
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: "Listen for, collect and convert multimessenger skymaps"
  doc_url: https://gocart.readthedocs.io
  dev_url: https://github.com/thespacedoctor/gocart

extra:
  recipe-maintainers:
    - thespacedoctor

