{% set name = "urdfdom-py" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ros/urdf_parser_py/archive/refs/tags/{{ version }}.tar.gz
  sha256: a0bd5e4f5eba54824ee7c09ce64d87f930f805d4ebc6f7fc8baa768c0bde3b28

build:
  script: {{ PYTHON }} -m pip install ./sdformat_mjcf -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools

test:
  source_files:
    - tests
  imports:
    - urdf_parser_py
  commands:
    - pip check
    - pytest ./test/ -v
  requires:
    - pip
    - pytest

about:
  home: https://github.com/ros/urdf_parser_py
  summary: 'Standalone URDF parser for Python.'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
