{% set version = "0.3.6" %}

package:
  name: jp-noui
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jp_noui/jp_noui-{{ version }}.tar.gz
  sha256: 67462a5d104ae0e1a0112122f544e2622ad78e662c8044d9676c13df9f0e64a7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - "jupyter-noui = jp-noui.app:main"

requirements:
  host:
    - hatch-jupyter-builder
    - jupyterlab >=3,<4
    - pip
    - python >=3.7

  run:
    - python >=3.7

  run_constrained:
    - jupyterlab >=3,<4

test:
  requires:
    - pip
    - jupyterlab >=3,<4
    - m2-grep  # [win]
  imports:
    - jp_noui
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "jp-noui.*v{{ version }}.*OK" labextensions
    - jupyter noui --version 2>&1 | grep -iE "{{ version }}"
    - jupyter noui --help 2>&1 | grep -iE "jupyter noui --config=my_config.json"

about:
  home: https://github.com/JoelStansbury/jp-noui
  summary: Hides jupyterlab UI elements for presentable notebook applications
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - {{ PREFIX }}/share/jupyter/labextensions/jp-noui/static/third-party-licenses.json


extra:
  recipe-maintainers:
    - JoelStansbury
