{% set version = "0.3.2" %}

package:
  name: jp-noui
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jp_noui/jp_noui-{{ version }}.tar.gz
  sha256: 3508ccd59686e64eedefee9e1ae0557e499ff6ea8125e5a3fe15f3f7804df6c0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv


requirements:
  host:
    - hatch-jupyter-builder
    - jupyterlab >=3,<4
    - pip
    - python >=3.7

  run:
    - python >=3.7

  run_constrained:
    - jupyterlab >=3,<4

test:
  requires:
    - pip
    - jupyterlab >=3,<4
    - m2-grep  # [win]
  imports:
    - jp_noui
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "jp-noui.*v{{ version }}.*OK" labextensions

about:
  home: https://github.com/JoelStansbury/jp-noui
  summary: Hides jupyterlab UI elements for presentable notebook applications
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - {{ SRC_DIR }}/jp-noui/labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - JoelStansbury
