{% set version = "0.3.4" %}

package:
  name: jp-noui
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jp_noui/jp_noui-{{ version }}.tar.gz
  sha256: 98ab266fa398311b1736a37dfcc6718bf903f7c190e94ac70f38ab5f5b57fca8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv


requirements:
  host:
    - hatch-jupyter-builder
    - jupyterlab >=3,<4
    - pip
    - python >=3.7

  run:
    - python >=3.7

  run_constrained:
    - jupyterlab >=3,<4

test:
  requires:
    - pip
    - jupyterlab >=3,<4
    - m2-grep  # [win]
  imports:
    - jp_noui
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "jp-noui.*v{{ version }}.*OK" labextensions

about:
  home: https://github.com/JoelStansbury/jp-noui
  summary: Hides jupyterlab UI elements for presentable notebook applications
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - JoelStansbury
