{% set name = "semimap" %}
# NOTE: Semimap does not have a release or a version.
#
# We rely on the last commit on upstream at the time of writing
# and simply use it as the version identifier.
#
# Q: Is there a better alternative?
{% set version = "de556c74721a5017f5a03faf2fbd1c6e5a768a32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hogliux/{{ name }}/archive/{{ version }}.tar.gz
  sha256: af4689afb3809664507e2ae77332650b658175d5382cbe63957707547d7ee76e

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}

test:
  requires:
    - {{ compiler('cxx') }}
  source_files:
    - test.cpp
  commands:
    - bash {{ RECIPE_DIR }}/run_test.sh  # [not win]
    - {{ RECIPE_DIR }}/run_test.bat  # [win]

about:
  home: https://github.com/hogliux/semimap/
  summary: 'A semi compile-/run-time associative map container with compile-time lookup and run-time storage'
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/hogliux/semimap

extra:
  recipe-maintainers:
    - jjerphan
    - DerThorsten
    - JohanMabille
