{% set name = "semimap" %}
# NOTE: Semimap does not have a release or a version.
#
# We rely on the last commit on upstream at the time of writing
# and simply use it as the version identifier.
#
# Q: Is there a better alternative?
{% set version = "9a106db4a8eb38a5b6e7c94a2a7addf8de7f6dd2" %}
{% set organization = "QuantStack" %}
{% set sha256 = "4d24673f4b83d8de1e573ef7cd06060e3e1a765e272f15a8d7d9a470f2a80b0e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ organization}}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  requires:
    - {{ compiler('cxx') }}
  source_files:
    - test.cpp
  commands:
    - bash {{ RECIPE_DIR }}/run_test.sh  # [not win]
    - {{ RECIPE_DIR }}/run_test.bat  # [win]

about:
  home: https://github.com/{{ organization }}/{{ name }}/
  summary: 'A semi compile-/run-time associative map container with compile-time lookup and run-time storage'
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/{{ organization }}/{{ name }}/

extra:
  recipe-maintainers:
    - jjerphan
    - DerThorsten
    - JohanMabille
